Public Class clsClipboardFilterItem
    Public Property GUID_FilterItem As String
    Public Property Name_FilterItem As String
    Public Property GUID_Tag_TableStart As String
    Public Property Name_Tag_TableStart As String
    Public Property NextLine_TableStart As Boolean
    Public Property GUID_Tag_TableEnd As String
    Public Property Name_Tag_TableEnd As String
    Public Property NextLine_TableEnd As Boolean
    Public Property GUID_Tag_RowStart As String
    Public Property Name_Tag_RowStart As String
    Public Property NextLine_RowStart As Boolean
    Public Property GUID_Tag_RowEnd As String
    Public Property Name_Tag_RowEnd As String
    Public Property NextLine_RowEnd As Boolean
    Public Property GUID_Tag_CellStart As String
    Public Property Name_Tag_CellStart As String
    Public Property NextLine_CellStart As Boolean
    Public Property GUID_Tag_CellEnd As String
    Public Property Name_Tag_CellEnd As String
    Public Property NextLine_CellEnd As Boolean
    Public Property GUID_Tag_HeaderStart As String
    Public Property Name_Tag_HeaderStart As String
    Public Property NextLine_HeaderStart As Boolean
    Public Property GUID_Tag_HeaderEnd As String
    Public Property Name_Tag_HeaderEnd As String
    Public Property NextLine_HeaderEnd As Boolean
    Public Property GUID_Tag_BoldStart As String
    Public Property Name_Tag_BoldStart As String
    Public Property NextLine_BoldStart As Boolean
    Public Property GUID_Tag_BoldEnd As String
    Public Property Name_Tag_BoldEnd As String
    Public Property NextLine_BoldEnd As Boolean
End Class
