//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18051
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace SilverOnt.OServiceAttributeTypes {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OServiceAttributeTypes.OServiceAttributeTypesSoap")]
    public interface OServiceAttributeTypesSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Config", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginConfig(System.AsyncCallback callback, object asyncState);
        
        SilverOnt.OServiceAttributeTypes.Config[] EndConfig(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AttributeTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginAttributeTypes(System.AsyncCallback callback, object asyncState);
        
        SilverOnt.OServiceAttributeTypes.clsOntologyItem[] EndAttributeTypes(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AttributeTypesByAttributeTypeGuid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginAttributeTypesByAttributeTypeGuid(string guidAttributeType, System.AsyncCallback callback, object asyncState);
        
        SilverOnt.OServiceAttributeTypes.clsOntologyItem[] EndAttributeTypesByAttributeTypeGuid(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AttributeTypesByAttributeTypeName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginAttributeTypesByAttributeTypeName(string nameAttributeType, bool strict, bool caseSensitive, System.AsyncCallback callback, object asyncState);
        
        SilverOnt.OServiceAttributeTypes.clsOntologyItem[] EndAttributeTypesByAttributeTypeName(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AttributeTypesByAttributeTypeIdDataType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginAttributeTypesByAttributeTypeIdDataType(string idDataType, System.AsyncCallback callback, object asyncState);
        
        SilverOnt.OServiceAttributeTypes.clsOntologyItem[] EndAttributeTypesByAttributeTypeIdDataType(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Config : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string configItemField;
        
        private string configValueStringField;
        
        private int configValueIntField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ConfigItem {
            get {
                return this.configItemField;
            }
            set {
                this.configItemField = value;
                this.RaisePropertyChanged("ConfigItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ConfigValueString {
            get {
                return this.configValueStringField;
            }
            set {
                this.configValueStringField = value;
                this.RaisePropertyChanged("ConfigValueString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ConfigValueInt {
            get {
                return this.configValueIntField;
            }
            set {
                this.configValueIntField = value;
                this.RaisePropertyChanged("ConfigValueInt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsOntologyItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private clsOntologyItem[] oList_RelField;
        
        private string gUIDField;
        
        private string gUID_ParentField;
        
        private string gUID_RelatedField;
        
        private string gUID_RelationField;
        
        private string nameField;
        
        private string captionField;
        
        private string additional1Field;
        
        private string additional2Field;
        
        private string typeField;
        
        private string filterField;
        
        private System.Nullable<int> imageIDField;
        
        private System.Nullable<int> versionField;
        
        private System.Nullable<long> levelField;
        
        private System.Nullable<bool> new_ItemField;
        
        private System.Nullable<bool> deletedField;
        
        private System.Nullable<bool> markField;
        
        private System.Nullable<bool> objectReferenceField;
        
        private System.Nullable<int> directionField;
        
        private System.Nullable<long> minField;
        
        private System.Nullable<long> max1Field;
        
        private System.Nullable<long> max2Field;
        
        private System.Nullable<long> val_LongField;
        
        private System.Nullable<bool> val_BoolField;
        
        private System.Nullable<System.DateTime> val_DateField;
        
        private System.Nullable<double> val_RealField;
        
        private string val_StringField;
        
        private System.Nullable<long> countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public clsOntologyItem[] OList_Rel {
            get {
                return this.oList_RelField;
            }
            set {
                this.oList_RelField = value;
                this.RaisePropertyChanged("OList_Rel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
                this.RaisePropertyChanged("GUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string GUID_Parent {
            get {
                return this.gUID_ParentField;
            }
            set {
                this.gUID_ParentField = value;
                this.RaisePropertyChanged("GUID_Parent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GUID_Related {
            get {
                return this.gUID_RelatedField;
            }
            set {
                this.gUID_RelatedField = value;
                this.RaisePropertyChanged("GUID_Related");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string GUID_Relation {
            get {
                return this.gUID_RelationField;
            }
            set {
                this.gUID_RelationField = value;
                this.RaisePropertyChanged("GUID_Relation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Caption {
            get {
                return this.captionField;
            }
            set {
                this.captionField = value;
                this.RaisePropertyChanged("Caption");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Additional1 {
            get {
                return this.additional1Field;
            }
            set {
                this.additional1Field = value;
                this.RaisePropertyChanged("Additional1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Additional2 {
            get {
                return this.additional2Field;
            }
            set {
                this.additional2Field = value;
                this.RaisePropertyChanged("Additional2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
                this.RaisePropertyChanged("Filter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<int> ImageID {
            get {
                return this.imageIDField;
            }
            set {
                this.imageIDField = value;
                this.RaisePropertyChanged("ImageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<long> Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("Level");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<bool> New_Item {
            get {
                return this.new_ItemField;
            }
            set {
                this.new_ItemField = value;
                this.RaisePropertyChanged("New_Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<bool> Deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
                this.RaisePropertyChanged("Deleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<bool> Mark {
            get {
                return this.markField;
            }
            set {
                this.markField = value;
                this.RaisePropertyChanged("Mark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<bool> ObjectReference {
            get {
                return this.objectReferenceField;
            }
            set {
                this.objectReferenceField = value;
                this.RaisePropertyChanged("ObjectReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<int> Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
                this.RaisePropertyChanged("Direction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<long> Min {
            get {
                return this.minField;
            }
            set {
                this.minField = value;
                this.RaisePropertyChanged("Min");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<long> Max1 {
            get {
                return this.max1Field;
            }
            set {
                this.max1Field = value;
                this.RaisePropertyChanged("Max1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public System.Nullable<long> Max2 {
            get {
                return this.max2Field;
            }
            set {
                this.max2Field = value;
                this.RaisePropertyChanged("Max2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public System.Nullable<long> Val_Long {
            get {
                return this.val_LongField;
            }
            set {
                this.val_LongField = value;
                this.RaisePropertyChanged("Val_Long");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public System.Nullable<bool> Val_Bool {
            get {
                return this.val_BoolField;
            }
            set {
                this.val_BoolField = value;
                this.RaisePropertyChanged("Val_Bool");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<System.DateTime> Val_Date {
            get {
                return this.val_DateField;
            }
            set {
                this.val_DateField = value;
                this.RaisePropertyChanged("Val_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<double> Val_Real {
            get {
                return this.val_RealField;
            }
            set {
                this.val_RealField = value;
                this.RaisePropertyChanged("Val_Real");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Val_String {
            get {
                return this.val_StringField;
            }
            set {
                this.val_StringField = value;
                this.RaisePropertyChanged("Val_String");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public System.Nullable<long> Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("Count");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OServiceAttributeTypesSoapChannel : SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfigCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConfigCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverOnt.OServiceAttributeTypes.Config[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverOnt.OServiceAttributeTypes.Config[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AttributeTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AttributeTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverOnt.OServiceAttributeTypes.clsOntologyItem[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverOnt.OServiceAttributeTypes.clsOntologyItem[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AttributeTypesByAttributeTypeGuidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AttributeTypesByAttributeTypeGuidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverOnt.OServiceAttributeTypes.clsOntologyItem[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverOnt.OServiceAttributeTypes.clsOntologyItem[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AttributeTypesByAttributeTypeNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AttributeTypesByAttributeTypeNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverOnt.OServiceAttributeTypes.clsOntologyItem[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverOnt.OServiceAttributeTypes.clsOntologyItem[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AttributeTypesByAttributeTypeIdDataTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AttributeTypesByAttributeTypeIdDataTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverOnt.OServiceAttributeTypes.clsOntologyItem[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverOnt.OServiceAttributeTypes.clsOntologyItem[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OServiceAttributeTypesSoapClient : System.ServiceModel.ClientBase<SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap>, SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap {
        
        private BeginOperationDelegate onBeginConfigDelegate;
        
        private EndOperationDelegate onEndConfigDelegate;
        
        private System.Threading.SendOrPostCallback onConfigCompletedDelegate;
        
        private BeginOperationDelegate onBeginAttributeTypesDelegate;
        
        private EndOperationDelegate onEndAttributeTypesDelegate;
        
        private System.Threading.SendOrPostCallback onAttributeTypesCompletedDelegate;
        
        private BeginOperationDelegate onBeginAttributeTypesByAttributeTypeGuidDelegate;
        
        private EndOperationDelegate onEndAttributeTypesByAttributeTypeGuidDelegate;
        
        private System.Threading.SendOrPostCallback onAttributeTypesByAttributeTypeGuidCompletedDelegate;
        
        private BeginOperationDelegate onBeginAttributeTypesByAttributeTypeNameDelegate;
        
        private EndOperationDelegate onEndAttributeTypesByAttributeTypeNameDelegate;
        
        private System.Threading.SendOrPostCallback onAttributeTypesByAttributeTypeNameCompletedDelegate;
        
        private BeginOperationDelegate onBeginAttributeTypesByAttributeTypeIdDataTypeDelegate;
        
        private EndOperationDelegate onEndAttributeTypesByAttributeTypeIdDataTypeDelegate;
        
        private System.Threading.SendOrPostCallback onAttributeTypesByAttributeTypeIdDataTypeCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public OServiceAttributeTypesSoapClient() {
        }
        
        public OServiceAttributeTypesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OServiceAttributeTypesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OServiceAttributeTypesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OServiceAttributeTypesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Der CookieContainer konnte nicht festgelegt werden. Stellen Sie sicher, dass die " +
                            "Bindung ein HttpCookieContainerBindingElement enthält.");
                }
            }
        }
        
        public event System.EventHandler<ConfigCompletedEventArgs> ConfigCompleted;
        
        public event System.EventHandler<AttributeTypesCompletedEventArgs> AttributeTypesCompleted;
        
        public event System.EventHandler<AttributeTypesByAttributeTypeGuidCompletedEventArgs> AttributeTypesByAttributeTypeGuidCompleted;
        
        public event System.EventHandler<AttributeTypesByAttributeTypeNameCompletedEventArgs> AttributeTypesByAttributeTypeNameCompleted;
        
        public event System.EventHandler<AttributeTypesByAttributeTypeIdDataTypeCompletedEventArgs> AttributeTypesByAttributeTypeIdDataTypeCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap.BeginConfig(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConfig(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverOnt.OServiceAttributeTypes.Config[] SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap.EndConfig(System.IAsyncResult result) {
            return base.Channel.EndConfig(result);
        }
        
        private System.IAsyncResult OnBeginConfig(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap)(this)).BeginConfig(callback, asyncState);
        }
        
        private object[] OnEndConfig(System.IAsyncResult result) {
            SilverOnt.OServiceAttributeTypes.Config[] retVal = ((SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap)(this)).EndConfig(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConfigCompleted(object state) {
            if ((this.ConfigCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConfigCompleted(this, new ConfigCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConfigAsync() {
            this.ConfigAsync(null);
        }
        
        public void ConfigAsync(object userState) {
            if ((this.onBeginConfigDelegate == null)) {
                this.onBeginConfigDelegate = new BeginOperationDelegate(this.OnBeginConfig);
            }
            if ((this.onEndConfigDelegate == null)) {
                this.onEndConfigDelegate = new EndOperationDelegate(this.OnEndConfig);
            }
            if ((this.onConfigCompletedDelegate == null)) {
                this.onConfigCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConfigCompleted);
            }
            base.InvokeAsync(this.onBeginConfigDelegate, null, this.onEndConfigDelegate, this.onConfigCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap.BeginAttributeTypes(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAttributeTypes(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverOnt.OServiceAttributeTypes.clsOntologyItem[] SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap.EndAttributeTypes(System.IAsyncResult result) {
            return base.Channel.EndAttributeTypes(result);
        }
        
        private System.IAsyncResult OnBeginAttributeTypes(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap)(this)).BeginAttributeTypes(callback, asyncState);
        }
        
        private object[] OnEndAttributeTypes(System.IAsyncResult result) {
            SilverOnt.OServiceAttributeTypes.clsOntologyItem[] retVal = ((SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap)(this)).EndAttributeTypes(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAttributeTypesCompleted(object state) {
            if ((this.AttributeTypesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AttributeTypesCompleted(this, new AttributeTypesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AttributeTypesAsync() {
            this.AttributeTypesAsync(null);
        }
        
        public void AttributeTypesAsync(object userState) {
            if ((this.onBeginAttributeTypesDelegate == null)) {
                this.onBeginAttributeTypesDelegate = new BeginOperationDelegate(this.OnBeginAttributeTypes);
            }
            if ((this.onEndAttributeTypesDelegate == null)) {
                this.onEndAttributeTypesDelegate = new EndOperationDelegate(this.OnEndAttributeTypes);
            }
            if ((this.onAttributeTypesCompletedDelegate == null)) {
                this.onAttributeTypesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAttributeTypesCompleted);
            }
            base.InvokeAsync(this.onBeginAttributeTypesDelegate, null, this.onEndAttributeTypesDelegate, this.onAttributeTypesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap.BeginAttributeTypesByAttributeTypeGuid(string guidAttributeType, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAttributeTypesByAttributeTypeGuid(guidAttributeType, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverOnt.OServiceAttributeTypes.clsOntologyItem[] SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap.EndAttributeTypesByAttributeTypeGuid(System.IAsyncResult result) {
            return base.Channel.EndAttributeTypesByAttributeTypeGuid(result);
        }
        
        private System.IAsyncResult OnBeginAttributeTypesByAttributeTypeGuid(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string guidAttributeType = ((string)(inValues[0]));
            return ((SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap)(this)).BeginAttributeTypesByAttributeTypeGuid(guidAttributeType, callback, asyncState);
        }
        
        private object[] OnEndAttributeTypesByAttributeTypeGuid(System.IAsyncResult result) {
            SilverOnt.OServiceAttributeTypes.clsOntologyItem[] retVal = ((SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap)(this)).EndAttributeTypesByAttributeTypeGuid(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAttributeTypesByAttributeTypeGuidCompleted(object state) {
            if ((this.AttributeTypesByAttributeTypeGuidCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AttributeTypesByAttributeTypeGuidCompleted(this, new AttributeTypesByAttributeTypeGuidCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AttributeTypesByAttributeTypeGuidAsync(string guidAttributeType) {
            this.AttributeTypesByAttributeTypeGuidAsync(guidAttributeType, null);
        }
        
        public void AttributeTypesByAttributeTypeGuidAsync(string guidAttributeType, object userState) {
            if ((this.onBeginAttributeTypesByAttributeTypeGuidDelegate == null)) {
                this.onBeginAttributeTypesByAttributeTypeGuidDelegate = new BeginOperationDelegate(this.OnBeginAttributeTypesByAttributeTypeGuid);
            }
            if ((this.onEndAttributeTypesByAttributeTypeGuidDelegate == null)) {
                this.onEndAttributeTypesByAttributeTypeGuidDelegate = new EndOperationDelegate(this.OnEndAttributeTypesByAttributeTypeGuid);
            }
            if ((this.onAttributeTypesByAttributeTypeGuidCompletedDelegate == null)) {
                this.onAttributeTypesByAttributeTypeGuidCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAttributeTypesByAttributeTypeGuidCompleted);
            }
            base.InvokeAsync(this.onBeginAttributeTypesByAttributeTypeGuidDelegate, new object[] {
                        guidAttributeType}, this.onEndAttributeTypesByAttributeTypeGuidDelegate, this.onAttributeTypesByAttributeTypeGuidCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap.BeginAttributeTypesByAttributeTypeName(string nameAttributeType, bool strict, bool caseSensitive, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAttributeTypesByAttributeTypeName(nameAttributeType, strict, caseSensitive, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverOnt.OServiceAttributeTypes.clsOntologyItem[] SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap.EndAttributeTypesByAttributeTypeName(System.IAsyncResult result) {
            return base.Channel.EndAttributeTypesByAttributeTypeName(result);
        }
        
        private System.IAsyncResult OnBeginAttributeTypesByAttributeTypeName(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string nameAttributeType = ((string)(inValues[0]));
            bool strict = ((bool)(inValues[1]));
            bool caseSensitive = ((bool)(inValues[2]));
            return ((SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap)(this)).BeginAttributeTypesByAttributeTypeName(nameAttributeType, strict, caseSensitive, callback, asyncState);
        }
        
        private object[] OnEndAttributeTypesByAttributeTypeName(System.IAsyncResult result) {
            SilverOnt.OServiceAttributeTypes.clsOntologyItem[] retVal = ((SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap)(this)).EndAttributeTypesByAttributeTypeName(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAttributeTypesByAttributeTypeNameCompleted(object state) {
            if ((this.AttributeTypesByAttributeTypeNameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AttributeTypesByAttributeTypeNameCompleted(this, new AttributeTypesByAttributeTypeNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AttributeTypesByAttributeTypeNameAsync(string nameAttributeType, bool strict, bool caseSensitive) {
            this.AttributeTypesByAttributeTypeNameAsync(nameAttributeType, strict, caseSensitive, null);
        }
        
        public void AttributeTypesByAttributeTypeNameAsync(string nameAttributeType, bool strict, bool caseSensitive, object userState) {
            if ((this.onBeginAttributeTypesByAttributeTypeNameDelegate == null)) {
                this.onBeginAttributeTypesByAttributeTypeNameDelegate = new BeginOperationDelegate(this.OnBeginAttributeTypesByAttributeTypeName);
            }
            if ((this.onEndAttributeTypesByAttributeTypeNameDelegate == null)) {
                this.onEndAttributeTypesByAttributeTypeNameDelegate = new EndOperationDelegate(this.OnEndAttributeTypesByAttributeTypeName);
            }
            if ((this.onAttributeTypesByAttributeTypeNameCompletedDelegate == null)) {
                this.onAttributeTypesByAttributeTypeNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAttributeTypesByAttributeTypeNameCompleted);
            }
            base.InvokeAsync(this.onBeginAttributeTypesByAttributeTypeNameDelegate, new object[] {
                        nameAttributeType,
                        strict,
                        caseSensitive}, this.onEndAttributeTypesByAttributeTypeNameDelegate, this.onAttributeTypesByAttributeTypeNameCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap.BeginAttributeTypesByAttributeTypeIdDataType(string idDataType, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAttributeTypesByAttributeTypeIdDataType(idDataType, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverOnt.OServiceAttributeTypes.clsOntologyItem[] SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap.EndAttributeTypesByAttributeTypeIdDataType(System.IAsyncResult result) {
            return base.Channel.EndAttributeTypesByAttributeTypeIdDataType(result);
        }
        
        private System.IAsyncResult OnBeginAttributeTypesByAttributeTypeIdDataType(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string idDataType = ((string)(inValues[0]));
            return ((SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap)(this)).BeginAttributeTypesByAttributeTypeIdDataType(idDataType, callback, asyncState);
        }
        
        private object[] OnEndAttributeTypesByAttributeTypeIdDataType(System.IAsyncResult result) {
            SilverOnt.OServiceAttributeTypes.clsOntologyItem[] retVal = ((SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap)(this)).EndAttributeTypesByAttributeTypeIdDataType(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAttributeTypesByAttributeTypeIdDataTypeCompleted(object state) {
            if ((this.AttributeTypesByAttributeTypeIdDataTypeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AttributeTypesByAttributeTypeIdDataTypeCompleted(this, new AttributeTypesByAttributeTypeIdDataTypeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AttributeTypesByAttributeTypeIdDataTypeAsync(string idDataType) {
            this.AttributeTypesByAttributeTypeIdDataTypeAsync(idDataType, null);
        }
        
        public void AttributeTypesByAttributeTypeIdDataTypeAsync(string idDataType, object userState) {
            if ((this.onBeginAttributeTypesByAttributeTypeIdDataTypeDelegate == null)) {
                this.onBeginAttributeTypesByAttributeTypeIdDataTypeDelegate = new BeginOperationDelegate(this.OnBeginAttributeTypesByAttributeTypeIdDataType);
            }
            if ((this.onEndAttributeTypesByAttributeTypeIdDataTypeDelegate == null)) {
                this.onEndAttributeTypesByAttributeTypeIdDataTypeDelegate = new EndOperationDelegate(this.OnEndAttributeTypesByAttributeTypeIdDataType);
            }
            if ((this.onAttributeTypesByAttributeTypeIdDataTypeCompletedDelegate == null)) {
                this.onAttributeTypesByAttributeTypeIdDataTypeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAttributeTypesByAttributeTypeIdDataTypeCompleted);
            }
            base.InvokeAsync(this.onBeginAttributeTypesByAttributeTypeIdDataTypeDelegate, new object[] {
                        idDataType}, this.onEndAttributeTypesByAttributeTypeIdDataTypeDelegate, this.onAttributeTypesByAttributeTypeIdDataTypeCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap CreateChannel() {
            return new OServiceAttributeTypesSoapClientChannel(this);
        }
        
        private class OServiceAttributeTypesSoapClientChannel : ChannelBase<SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap>, SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap {
            
            public OServiceAttributeTypesSoapClientChannel(System.ServiceModel.ClientBase<SilverOnt.OServiceAttributeTypes.OServiceAttributeTypesSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginConfig(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Config", _args, callback, asyncState);
                return _result;
            }
            
            public SilverOnt.OServiceAttributeTypes.Config[] EndConfig(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverOnt.OServiceAttributeTypes.Config[] _result = ((SilverOnt.OServiceAttributeTypes.Config[])(base.EndInvoke("Config", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAttributeTypes(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("AttributeTypes", _args, callback, asyncState);
                return _result;
            }
            
            public SilverOnt.OServiceAttributeTypes.clsOntologyItem[] EndAttributeTypes(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverOnt.OServiceAttributeTypes.clsOntologyItem[] _result = ((SilverOnt.OServiceAttributeTypes.clsOntologyItem[])(base.EndInvoke("AttributeTypes", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAttributeTypesByAttributeTypeGuid(string guidAttributeType, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = guidAttributeType;
                System.IAsyncResult _result = base.BeginInvoke("AttributeTypesByAttributeTypeGuid", _args, callback, asyncState);
                return _result;
            }
            
            public SilverOnt.OServiceAttributeTypes.clsOntologyItem[] EndAttributeTypesByAttributeTypeGuid(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverOnt.OServiceAttributeTypes.clsOntologyItem[] _result = ((SilverOnt.OServiceAttributeTypes.clsOntologyItem[])(base.EndInvoke("AttributeTypesByAttributeTypeGuid", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAttributeTypesByAttributeTypeName(string nameAttributeType, bool strict, bool caseSensitive, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = nameAttributeType;
                _args[1] = strict;
                _args[2] = caseSensitive;
                System.IAsyncResult _result = base.BeginInvoke("AttributeTypesByAttributeTypeName", _args, callback, asyncState);
                return _result;
            }
            
            public SilverOnt.OServiceAttributeTypes.clsOntologyItem[] EndAttributeTypesByAttributeTypeName(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverOnt.OServiceAttributeTypes.clsOntologyItem[] _result = ((SilverOnt.OServiceAttributeTypes.clsOntologyItem[])(base.EndInvoke("AttributeTypesByAttributeTypeName", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAttributeTypesByAttributeTypeIdDataType(string idDataType, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = idDataType;
                System.IAsyncResult _result = base.BeginInvoke("AttributeTypesByAttributeTypeIdDataType", _args, callback, asyncState);
                return _result;
            }
            
            public SilverOnt.OServiceAttributeTypes.clsOntologyItem[] EndAttributeTypesByAttributeTypeIdDataType(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverOnt.OServiceAttributeTypes.clsOntologyItem[] _result = ((SilverOnt.OServiceAttributeTypes.clsOntologyItem[])(base.EndInvoke("AttributeTypesByAttributeTypeIdDataType", _args, result)));
                return _result;
            }
        }
    }
}
