//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18051
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace SilverOnt.OServiceObjects {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OServiceObjects.OServiceObjectsSoap")]
    public interface OServiceObjectsSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Config", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginConfig(System.AsyncCallback callback, object asyncState);
        
        SilverOnt.OServiceObjects.Config[] EndConfig(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Objects", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginObjects(System.AsyncCallback callback, object asyncState);
        
        SilverOnt.OServiceObjects.clsOntologyItem[] EndObjects(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ObjectsByGuid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginObjectsByGuid(string guid, System.AsyncCallback callback, object asyncState);
        
        SilverOnt.OServiceObjects.clsOntologyItem[] EndObjectsByGuid(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ObjectsByName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginObjectsByName(string name, bool exact, System.AsyncCallback callback, object asyncState);
        
        SilverOnt.OServiceObjects.clsOntologyItem[] EndObjectsByName(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ObjectsByGuidParent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginObjectsByGuidParent(string guidParent, System.AsyncCallback callback, object asyncState);
        
        SilverOnt.OServiceObjects.clsOntologyItem[] EndObjectsByGuidParent(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ObjectsByGuidParentAndName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginObjectsByGuidParentAndName(string guidParent, string name, bool exact, System.AsyncCallback callback, object asyncState);
        
        SilverOnt.OServiceObjects.clsOntologyItem[] EndObjectsByGuidParentAndName(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Config : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string configItemField;
        
        private string configValueStringField;
        
        private int configValueIntField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ConfigItem {
            get {
                return this.configItemField;
            }
            set {
                this.configItemField = value;
                this.RaisePropertyChanged("ConfigItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ConfigValueString {
            get {
                return this.configValueStringField;
            }
            set {
                this.configValueStringField = value;
                this.RaisePropertyChanged("ConfigValueString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ConfigValueInt {
            get {
                return this.configValueIntField;
            }
            set {
                this.configValueIntField = value;
                this.RaisePropertyChanged("ConfigValueInt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsOntologyItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private clsOntologyItem[] oList_RelField;
        
        private string gUIDField;
        
        private string gUID_ParentField;
        
        private string gUID_RelatedField;
        
        private string gUID_RelationField;
        
        private string nameField;
        
        private string captionField;
        
        private string additional1Field;
        
        private string additional2Field;
        
        private string typeField;
        
        private string filterField;
        
        private System.Nullable<int> imageIDField;
        
        private System.Nullable<int> versionField;
        
        private System.Nullable<long> levelField;
        
        private System.Nullable<bool> new_ItemField;
        
        private System.Nullable<bool> deletedField;
        
        private System.Nullable<bool> markField;
        
        private System.Nullable<bool> objectReferenceField;
        
        private System.Nullable<int> directionField;
        
        private System.Nullable<long> minField;
        
        private System.Nullable<long> max1Field;
        
        private System.Nullable<long> max2Field;
        
        private System.Nullable<long> val_LongField;
        
        private System.Nullable<bool> val_BoolField;
        
        private System.Nullable<System.DateTime> val_DateField;
        
        private System.Nullable<double> val_RealField;
        
        private string val_StringField;
        
        private System.Nullable<long> countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public clsOntologyItem[] OList_Rel {
            get {
                return this.oList_RelField;
            }
            set {
                this.oList_RelField = value;
                this.RaisePropertyChanged("OList_Rel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
                this.RaisePropertyChanged("GUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string GUID_Parent {
            get {
                return this.gUID_ParentField;
            }
            set {
                this.gUID_ParentField = value;
                this.RaisePropertyChanged("GUID_Parent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GUID_Related {
            get {
                return this.gUID_RelatedField;
            }
            set {
                this.gUID_RelatedField = value;
                this.RaisePropertyChanged("GUID_Related");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string GUID_Relation {
            get {
                return this.gUID_RelationField;
            }
            set {
                this.gUID_RelationField = value;
                this.RaisePropertyChanged("GUID_Relation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Caption {
            get {
                return this.captionField;
            }
            set {
                this.captionField = value;
                this.RaisePropertyChanged("Caption");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Additional1 {
            get {
                return this.additional1Field;
            }
            set {
                this.additional1Field = value;
                this.RaisePropertyChanged("Additional1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Additional2 {
            get {
                return this.additional2Field;
            }
            set {
                this.additional2Field = value;
                this.RaisePropertyChanged("Additional2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
                this.RaisePropertyChanged("Filter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<int> ImageID {
            get {
                return this.imageIDField;
            }
            set {
                this.imageIDField = value;
                this.RaisePropertyChanged("ImageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<long> Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("Level");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<bool> New_Item {
            get {
                return this.new_ItemField;
            }
            set {
                this.new_ItemField = value;
                this.RaisePropertyChanged("New_Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<bool> Deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
                this.RaisePropertyChanged("Deleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<bool> Mark {
            get {
                return this.markField;
            }
            set {
                this.markField = value;
                this.RaisePropertyChanged("Mark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<bool> ObjectReference {
            get {
                return this.objectReferenceField;
            }
            set {
                this.objectReferenceField = value;
                this.RaisePropertyChanged("ObjectReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<int> Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
                this.RaisePropertyChanged("Direction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<long> Min {
            get {
                return this.minField;
            }
            set {
                this.minField = value;
                this.RaisePropertyChanged("Min");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<long> Max1 {
            get {
                return this.max1Field;
            }
            set {
                this.max1Field = value;
                this.RaisePropertyChanged("Max1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public System.Nullable<long> Max2 {
            get {
                return this.max2Field;
            }
            set {
                this.max2Field = value;
                this.RaisePropertyChanged("Max2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public System.Nullable<long> Val_Long {
            get {
                return this.val_LongField;
            }
            set {
                this.val_LongField = value;
                this.RaisePropertyChanged("Val_Long");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public System.Nullable<bool> Val_Bool {
            get {
                return this.val_BoolField;
            }
            set {
                this.val_BoolField = value;
                this.RaisePropertyChanged("Val_Bool");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<System.DateTime> Val_Date {
            get {
                return this.val_DateField;
            }
            set {
                this.val_DateField = value;
                this.RaisePropertyChanged("Val_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<double> Val_Real {
            get {
                return this.val_RealField;
            }
            set {
                this.val_RealField = value;
                this.RaisePropertyChanged("Val_Real");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Val_String {
            get {
                return this.val_StringField;
            }
            set {
                this.val_StringField = value;
                this.RaisePropertyChanged("Val_String");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public System.Nullable<long> Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("Count");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OServiceObjectsSoapChannel : SilverOnt.OServiceObjects.OServiceObjectsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfigCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConfigCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverOnt.OServiceObjects.Config[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverOnt.OServiceObjects.Config[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObjectsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ObjectsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverOnt.OServiceObjects.clsOntologyItem[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverOnt.OServiceObjects.clsOntologyItem[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObjectsByGuidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ObjectsByGuidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverOnt.OServiceObjects.clsOntologyItem[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverOnt.OServiceObjects.clsOntologyItem[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObjectsByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ObjectsByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverOnt.OServiceObjects.clsOntologyItem[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverOnt.OServiceObjects.clsOntologyItem[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObjectsByGuidParentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ObjectsByGuidParentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverOnt.OServiceObjects.clsOntologyItem[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverOnt.OServiceObjects.clsOntologyItem[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObjectsByGuidParentAndNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ObjectsByGuidParentAndNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverOnt.OServiceObjects.clsOntologyItem[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverOnt.OServiceObjects.clsOntologyItem[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OServiceObjectsSoapClient : System.ServiceModel.ClientBase<SilverOnt.OServiceObjects.OServiceObjectsSoap>, SilverOnt.OServiceObjects.OServiceObjectsSoap {
        
        private BeginOperationDelegate onBeginConfigDelegate;
        
        private EndOperationDelegate onEndConfigDelegate;
        
        private System.Threading.SendOrPostCallback onConfigCompletedDelegate;
        
        private BeginOperationDelegate onBeginObjectsDelegate;
        
        private EndOperationDelegate onEndObjectsDelegate;
        
        private System.Threading.SendOrPostCallback onObjectsCompletedDelegate;
        
        private BeginOperationDelegate onBeginObjectsByGuidDelegate;
        
        private EndOperationDelegate onEndObjectsByGuidDelegate;
        
        private System.Threading.SendOrPostCallback onObjectsByGuidCompletedDelegate;
        
        private BeginOperationDelegate onBeginObjectsByNameDelegate;
        
        private EndOperationDelegate onEndObjectsByNameDelegate;
        
        private System.Threading.SendOrPostCallback onObjectsByNameCompletedDelegate;
        
        private BeginOperationDelegate onBeginObjectsByGuidParentDelegate;
        
        private EndOperationDelegate onEndObjectsByGuidParentDelegate;
        
        private System.Threading.SendOrPostCallback onObjectsByGuidParentCompletedDelegate;
        
        private BeginOperationDelegate onBeginObjectsByGuidParentAndNameDelegate;
        
        private EndOperationDelegate onEndObjectsByGuidParentAndNameDelegate;
        
        private System.Threading.SendOrPostCallback onObjectsByGuidParentAndNameCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public OServiceObjectsSoapClient() {
        }
        
        public OServiceObjectsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OServiceObjectsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OServiceObjectsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OServiceObjectsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Der CookieContainer konnte nicht festgelegt werden. Stellen Sie sicher, dass die " +
                            "Bindung ein HttpCookieContainerBindingElement enthält.");
                }
            }
        }
        
        public event System.EventHandler<ConfigCompletedEventArgs> ConfigCompleted;
        
        public event System.EventHandler<ObjectsCompletedEventArgs> ObjectsCompleted;
        
        public event System.EventHandler<ObjectsByGuidCompletedEventArgs> ObjectsByGuidCompleted;
        
        public event System.EventHandler<ObjectsByNameCompletedEventArgs> ObjectsByNameCompleted;
        
        public event System.EventHandler<ObjectsByGuidParentCompletedEventArgs> ObjectsByGuidParentCompleted;
        
        public event System.EventHandler<ObjectsByGuidParentAndNameCompletedEventArgs> ObjectsByGuidParentAndNameCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverOnt.OServiceObjects.OServiceObjectsSoap.BeginConfig(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConfig(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverOnt.OServiceObjects.Config[] SilverOnt.OServiceObjects.OServiceObjectsSoap.EndConfig(System.IAsyncResult result) {
            return base.Channel.EndConfig(result);
        }
        
        private System.IAsyncResult OnBeginConfig(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SilverOnt.OServiceObjects.OServiceObjectsSoap)(this)).BeginConfig(callback, asyncState);
        }
        
        private object[] OnEndConfig(System.IAsyncResult result) {
            SilverOnt.OServiceObjects.Config[] retVal = ((SilverOnt.OServiceObjects.OServiceObjectsSoap)(this)).EndConfig(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConfigCompleted(object state) {
            if ((this.ConfigCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConfigCompleted(this, new ConfigCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConfigAsync() {
            this.ConfigAsync(null);
        }
        
        public void ConfigAsync(object userState) {
            if ((this.onBeginConfigDelegate == null)) {
                this.onBeginConfigDelegate = new BeginOperationDelegate(this.OnBeginConfig);
            }
            if ((this.onEndConfigDelegate == null)) {
                this.onEndConfigDelegate = new EndOperationDelegate(this.OnEndConfig);
            }
            if ((this.onConfigCompletedDelegate == null)) {
                this.onConfigCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConfigCompleted);
            }
            base.InvokeAsync(this.onBeginConfigDelegate, null, this.onEndConfigDelegate, this.onConfigCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverOnt.OServiceObjects.OServiceObjectsSoap.BeginObjects(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginObjects(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverOnt.OServiceObjects.clsOntologyItem[] SilverOnt.OServiceObjects.OServiceObjectsSoap.EndObjects(System.IAsyncResult result) {
            return base.Channel.EndObjects(result);
        }
        
        private System.IAsyncResult OnBeginObjects(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SilverOnt.OServiceObjects.OServiceObjectsSoap)(this)).BeginObjects(callback, asyncState);
        }
        
        private object[] OnEndObjects(System.IAsyncResult result) {
            SilverOnt.OServiceObjects.clsOntologyItem[] retVal = ((SilverOnt.OServiceObjects.OServiceObjectsSoap)(this)).EndObjects(result);
            return new object[] {
                    retVal};
        }
        
        private void OnObjectsCompleted(object state) {
            if ((this.ObjectsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ObjectsCompleted(this, new ObjectsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ObjectsAsync() {
            this.ObjectsAsync(null);
        }
        
        public void ObjectsAsync(object userState) {
            if ((this.onBeginObjectsDelegate == null)) {
                this.onBeginObjectsDelegate = new BeginOperationDelegate(this.OnBeginObjects);
            }
            if ((this.onEndObjectsDelegate == null)) {
                this.onEndObjectsDelegate = new EndOperationDelegate(this.OnEndObjects);
            }
            if ((this.onObjectsCompletedDelegate == null)) {
                this.onObjectsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnObjectsCompleted);
            }
            base.InvokeAsync(this.onBeginObjectsDelegate, null, this.onEndObjectsDelegate, this.onObjectsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverOnt.OServiceObjects.OServiceObjectsSoap.BeginObjectsByGuid(string guid, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginObjectsByGuid(guid, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverOnt.OServiceObjects.clsOntologyItem[] SilverOnt.OServiceObjects.OServiceObjectsSoap.EndObjectsByGuid(System.IAsyncResult result) {
            return base.Channel.EndObjectsByGuid(result);
        }
        
        private System.IAsyncResult OnBeginObjectsByGuid(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string guid = ((string)(inValues[0]));
            return ((SilverOnt.OServiceObjects.OServiceObjectsSoap)(this)).BeginObjectsByGuid(guid, callback, asyncState);
        }
        
        private object[] OnEndObjectsByGuid(System.IAsyncResult result) {
            SilverOnt.OServiceObjects.clsOntologyItem[] retVal = ((SilverOnt.OServiceObjects.OServiceObjectsSoap)(this)).EndObjectsByGuid(result);
            return new object[] {
                    retVal};
        }
        
        private void OnObjectsByGuidCompleted(object state) {
            if ((this.ObjectsByGuidCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ObjectsByGuidCompleted(this, new ObjectsByGuidCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ObjectsByGuidAsync(string guid) {
            this.ObjectsByGuidAsync(guid, null);
        }
        
        public void ObjectsByGuidAsync(string guid, object userState) {
            if ((this.onBeginObjectsByGuidDelegate == null)) {
                this.onBeginObjectsByGuidDelegate = new BeginOperationDelegate(this.OnBeginObjectsByGuid);
            }
            if ((this.onEndObjectsByGuidDelegate == null)) {
                this.onEndObjectsByGuidDelegate = new EndOperationDelegate(this.OnEndObjectsByGuid);
            }
            if ((this.onObjectsByGuidCompletedDelegate == null)) {
                this.onObjectsByGuidCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnObjectsByGuidCompleted);
            }
            base.InvokeAsync(this.onBeginObjectsByGuidDelegate, new object[] {
                        guid}, this.onEndObjectsByGuidDelegate, this.onObjectsByGuidCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverOnt.OServiceObjects.OServiceObjectsSoap.BeginObjectsByName(string name, bool exact, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginObjectsByName(name, exact, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverOnt.OServiceObjects.clsOntologyItem[] SilverOnt.OServiceObjects.OServiceObjectsSoap.EndObjectsByName(System.IAsyncResult result) {
            return base.Channel.EndObjectsByName(result);
        }
        
        private System.IAsyncResult OnBeginObjectsByName(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string name = ((string)(inValues[0]));
            bool exact = ((bool)(inValues[1]));
            return ((SilverOnt.OServiceObjects.OServiceObjectsSoap)(this)).BeginObjectsByName(name, exact, callback, asyncState);
        }
        
        private object[] OnEndObjectsByName(System.IAsyncResult result) {
            SilverOnt.OServiceObjects.clsOntologyItem[] retVal = ((SilverOnt.OServiceObjects.OServiceObjectsSoap)(this)).EndObjectsByName(result);
            return new object[] {
                    retVal};
        }
        
        private void OnObjectsByNameCompleted(object state) {
            if ((this.ObjectsByNameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ObjectsByNameCompleted(this, new ObjectsByNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ObjectsByNameAsync(string name, bool exact) {
            this.ObjectsByNameAsync(name, exact, null);
        }
        
        public void ObjectsByNameAsync(string name, bool exact, object userState) {
            if ((this.onBeginObjectsByNameDelegate == null)) {
                this.onBeginObjectsByNameDelegate = new BeginOperationDelegate(this.OnBeginObjectsByName);
            }
            if ((this.onEndObjectsByNameDelegate == null)) {
                this.onEndObjectsByNameDelegate = new EndOperationDelegate(this.OnEndObjectsByName);
            }
            if ((this.onObjectsByNameCompletedDelegate == null)) {
                this.onObjectsByNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnObjectsByNameCompleted);
            }
            base.InvokeAsync(this.onBeginObjectsByNameDelegate, new object[] {
                        name,
                        exact}, this.onEndObjectsByNameDelegate, this.onObjectsByNameCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverOnt.OServiceObjects.OServiceObjectsSoap.BeginObjectsByGuidParent(string guidParent, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginObjectsByGuidParent(guidParent, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverOnt.OServiceObjects.clsOntologyItem[] SilverOnt.OServiceObjects.OServiceObjectsSoap.EndObjectsByGuidParent(System.IAsyncResult result) {
            return base.Channel.EndObjectsByGuidParent(result);
        }
        
        private System.IAsyncResult OnBeginObjectsByGuidParent(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string guidParent = ((string)(inValues[0]));
            return ((SilverOnt.OServiceObjects.OServiceObjectsSoap)(this)).BeginObjectsByGuidParent(guidParent, callback, asyncState);
        }
        
        private object[] OnEndObjectsByGuidParent(System.IAsyncResult result) {
            SilverOnt.OServiceObjects.clsOntologyItem[] retVal = ((SilverOnt.OServiceObjects.OServiceObjectsSoap)(this)).EndObjectsByGuidParent(result);
            return new object[] {
                    retVal};
        }
        
        private void OnObjectsByGuidParentCompleted(object state) {
            if ((this.ObjectsByGuidParentCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ObjectsByGuidParentCompleted(this, new ObjectsByGuidParentCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ObjectsByGuidParentAsync(string guidParent) {
            this.ObjectsByGuidParentAsync(guidParent, null);
        }
        
        public void ObjectsByGuidParentAsync(string guidParent, object userState) {
            if ((this.onBeginObjectsByGuidParentDelegate == null)) {
                this.onBeginObjectsByGuidParentDelegate = new BeginOperationDelegate(this.OnBeginObjectsByGuidParent);
            }
            if ((this.onEndObjectsByGuidParentDelegate == null)) {
                this.onEndObjectsByGuidParentDelegate = new EndOperationDelegate(this.OnEndObjectsByGuidParent);
            }
            if ((this.onObjectsByGuidParentCompletedDelegate == null)) {
                this.onObjectsByGuidParentCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnObjectsByGuidParentCompleted);
            }
            base.InvokeAsync(this.onBeginObjectsByGuidParentDelegate, new object[] {
                        guidParent}, this.onEndObjectsByGuidParentDelegate, this.onObjectsByGuidParentCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverOnt.OServiceObjects.OServiceObjectsSoap.BeginObjectsByGuidParentAndName(string guidParent, string name, bool exact, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginObjectsByGuidParentAndName(guidParent, name, exact, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverOnt.OServiceObjects.clsOntologyItem[] SilverOnt.OServiceObjects.OServiceObjectsSoap.EndObjectsByGuidParentAndName(System.IAsyncResult result) {
            return base.Channel.EndObjectsByGuidParentAndName(result);
        }
        
        private System.IAsyncResult OnBeginObjectsByGuidParentAndName(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string guidParent = ((string)(inValues[0]));
            string name = ((string)(inValues[1]));
            bool exact = ((bool)(inValues[2]));
            return ((SilverOnt.OServiceObjects.OServiceObjectsSoap)(this)).BeginObjectsByGuidParentAndName(guidParent, name, exact, callback, asyncState);
        }
        
        private object[] OnEndObjectsByGuidParentAndName(System.IAsyncResult result) {
            SilverOnt.OServiceObjects.clsOntologyItem[] retVal = ((SilverOnt.OServiceObjects.OServiceObjectsSoap)(this)).EndObjectsByGuidParentAndName(result);
            return new object[] {
                    retVal};
        }
        
        private void OnObjectsByGuidParentAndNameCompleted(object state) {
            if ((this.ObjectsByGuidParentAndNameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ObjectsByGuidParentAndNameCompleted(this, new ObjectsByGuidParentAndNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ObjectsByGuidParentAndNameAsync(string guidParent, string name, bool exact) {
            this.ObjectsByGuidParentAndNameAsync(guidParent, name, exact, null);
        }
        
        public void ObjectsByGuidParentAndNameAsync(string guidParent, string name, bool exact, object userState) {
            if ((this.onBeginObjectsByGuidParentAndNameDelegate == null)) {
                this.onBeginObjectsByGuidParentAndNameDelegate = new BeginOperationDelegate(this.OnBeginObjectsByGuidParentAndName);
            }
            if ((this.onEndObjectsByGuidParentAndNameDelegate == null)) {
                this.onEndObjectsByGuidParentAndNameDelegate = new EndOperationDelegate(this.OnEndObjectsByGuidParentAndName);
            }
            if ((this.onObjectsByGuidParentAndNameCompletedDelegate == null)) {
                this.onObjectsByGuidParentAndNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnObjectsByGuidParentAndNameCompleted);
            }
            base.InvokeAsync(this.onBeginObjectsByGuidParentAndNameDelegate, new object[] {
                        guidParent,
                        name,
                        exact}, this.onEndObjectsByGuidParentAndNameDelegate, this.onObjectsByGuidParentAndNameCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SilverOnt.OServiceObjects.OServiceObjectsSoap CreateChannel() {
            return new OServiceObjectsSoapClientChannel(this);
        }
        
        private class OServiceObjectsSoapClientChannel : ChannelBase<SilverOnt.OServiceObjects.OServiceObjectsSoap>, SilverOnt.OServiceObjects.OServiceObjectsSoap {
            
            public OServiceObjectsSoapClientChannel(System.ServiceModel.ClientBase<SilverOnt.OServiceObjects.OServiceObjectsSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginConfig(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Config", _args, callback, asyncState);
                return _result;
            }
            
            public SilverOnt.OServiceObjects.Config[] EndConfig(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverOnt.OServiceObjects.Config[] _result = ((SilverOnt.OServiceObjects.Config[])(base.EndInvoke("Config", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginObjects(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Objects", _args, callback, asyncState);
                return _result;
            }
            
            public SilverOnt.OServiceObjects.clsOntologyItem[] EndObjects(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverOnt.OServiceObjects.clsOntologyItem[] _result = ((SilverOnt.OServiceObjects.clsOntologyItem[])(base.EndInvoke("Objects", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginObjectsByGuid(string guid, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = guid;
                System.IAsyncResult _result = base.BeginInvoke("ObjectsByGuid", _args, callback, asyncState);
                return _result;
            }
            
            public SilverOnt.OServiceObjects.clsOntologyItem[] EndObjectsByGuid(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverOnt.OServiceObjects.clsOntologyItem[] _result = ((SilverOnt.OServiceObjects.clsOntologyItem[])(base.EndInvoke("ObjectsByGuid", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginObjectsByName(string name, bool exact, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = name;
                _args[1] = exact;
                System.IAsyncResult _result = base.BeginInvoke("ObjectsByName", _args, callback, asyncState);
                return _result;
            }
            
            public SilverOnt.OServiceObjects.clsOntologyItem[] EndObjectsByName(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverOnt.OServiceObjects.clsOntologyItem[] _result = ((SilverOnt.OServiceObjects.clsOntologyItem[])(base.EndInvoke("ObjectsByName", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginObjectsByGuidParent(string guidParent, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = guidParent;
                System.IAsyncResult _result = base.BeginInvoke("ObjectsByGuidParent", _args, callback, asyncState);
                return _result;
            }
            
            public SilverOnt.OServiceObjects.clsOntologyItem[] EndObjectsByGuidParent(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverOnt.OServiceObjects.clsOntologyItem[] _result = ((SilverOnt.OServiceObjects.clsOntologyItem[])(base.EndInvoke("ObjectsByGuidParent", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginObjectsByGuidParentAndName(string guidParent, string name, bool exact, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = guidParent;
                _args[1] = name;
                _args[2] = exact;
                System.IAsyncResult _result = base.BeginInvoke("ObjectsByGuidParentAndName", _args, callback, asyncState);
                return _result;
            }
            
            public SilverOnt.OServiceObjects.clsOntologyItem[] EndObjectsByGuidParentAndName(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverOnt.OServiceObjects.clsOntologyItem[] _result = ((SilverOnt.OServiceObjects.clsOntologyItem[])(base.EndInvoke("ObjectsByGuidParentAndName", _args, result)));
                return _result;
            }
        }
    }
}
