//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18051
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace SilverOnt.OServiceClasses {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OServiceClasses.OServiceClassesSoap")]
    public interface OServiceClassesSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Config", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginConfig(System.AsyncCallback callback, object asyncState);
        
        SilverOnt.OServiceClasses.Config[] EndConfig(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Classes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginClasses(System.AsyncCallback callback, object asyncState);
        
        SilverOnt.OServiceClasses.clsOntologyItem[] EndClasses(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ClassesByGuid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginClassesByGuid(string guid, System.AsyncCallback callback, object asyncState);
        
        SilverOnt.OServiceClasses.clsOntologyItem[] EndClassesByGuid(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ClassesByName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginClassesByName(string name, bool strict, bool caseSensitive, System.AsyncCallback callback, object asyncState);
        
        SilverOnt.OServiceClasses.clsOntologyItem[] EndClassesByName(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Config : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string configItemField;
        
        private string configValueStringField;
        
        private int configValueIntField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ConfigItem {
            get {
                return this.configItemField;
            }
            set {
                this.configItemField = value;
                this.RaisePropertyChanged("ConfigItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ConfigValueString {
            get {
                return this.configValueStringField;
            }
            set {
                this.configValueStringField = value;
                this.RaisePropertyChanged("ConfigValueString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ConfigValueInt {
            get {
                return this.configValueIntField;
            }
            set {
                this.configValueIntField = value;
                this.RaisePropertyChanged("ConfigValueInt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsOntologyItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private clsOntologyItem[] oList_RelField;
        
        private string gUIDField;
        
        private string gUID_ParentField;
        
        private string gUID_RelatedField;
        
        private string gUID_RelationField;
        
        private string nameField;
        
        private string captionField;
        
        private string additional1Field;
        
        private string additional2Field;
        
        private string typeField;
        
        private string filterField;
        
        private System.Nullable<int> imageIDField;
        
        private System.Nullable<int> versionField;
        
        private System.Nullable<long> levelField;
        
        private System.Nullable<bool> new_ItemField;
        
        private System.Nullable<bool> deletedField;
        
        private System.Nullable<bool> markField;
        
        private System.Nullable<bool> objectReferenceField;
        
        private System.Nullable<int> directionField;
        
        private System.Nullable<long> minField;
        
        private System.Nullable<long> max1Field;
        
        private System.Nullable<long> max2Field;
        
        private System.Nullable<long> val_LongField;
        
        private System.Nullable<bool> val_BoolField;
        
        private System.Nullable<System.DateTime> val_DateField;
        
        private System.Nullable<double> val_RealField;
        
        private string val_StringField;
        
        private System.Nullable<long> countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public clsOntologyItem[] OList_Rel {
            get {
                return this.oList_RelField;
            }
            set {
                this.oList_RelField = value;
                this.RaisePropertyChanged("OList_Rel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
                this.RaisePropertyChanged("GUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string GUID_Parent {
            get {
                return this.gUID_ParentField;
            }
            set {
                this.gUID_ParentField = value;
                this.RaisePropertyChanged("GUID_Parent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GUID_Related {
            get {
                return this.gUID_RelatedField;
            }
            set {
                this.gUID_RelatedField = value;
                this.RaisePropertyChanged("GUID_Related");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string GUID_Relation {
            get {
                return this.gUID_RelationField;
            }
            set {
                this.gUID_RelationField = value;
                this.RaisePropertyChanged("GUID_Relation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Caption {
            get {
                return this.captionField;
            }
            set {
                this.captionField = value;
                this.RaisePropertyChanged("Caption");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Additional1 {
            get {
                return this.additional1Field;
            }
            set {
                this.additional1Field = value;
                this.RaisePropertyChanged("Additional1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Additional2 {
            get {
                return this.additional2Field;
            }
            set {
                this.additional2Field = value;
                this.RaisePropertyChanged("Additional2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
                this.RaisePropertyChanged("Filter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<int> ImageID {
            get {
                return this.imageIDField;
            }
            set {
                this.imageIDField = value;
                this.RaisePropertyChanged("ImageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<long> Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("Level");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<bool> New_Item {
            get {
                return this.new_ItemField;
            }
            set {
                this.new_ItemField = value;
                this.RaisePropertyChanged("New_Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<bool> Deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
                this.RaisePropertyChanged("Deleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<bool> Mark {
            get {
                return this.markField;
            }
            set {
                this.markField = value;
                this.RaisePropertyChanged("Mark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<bool> ObjectReference {
            get {
                return this.objectReferenceField;
            }
            set {
                this.objectReferenceField = value;
                this.RaisePropertyChanged("ObjectReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<int> Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
                this.RaisePropertyChanged("Direction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<long> Min {
            get {
                return this.minField;
            }
            set {
                this.minField = value;
                this.RaisePropertyChanged("Min");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<long> Max1 {
            get {
                return this.max1Field;
            }
            set {
                this.max1Field = value;
                this.RaisePropertyChanged("Max1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public System.Nullable<long> Max2 {
            get {
                return this.max2Field;
            }
            set {
                this.max2Field = value;
                this.RaisePropertyChanged("Max2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public System.Nullable<long> Val_Long {
            get {
                return this.val_LongField;
            }
            set {
                this.val_LongField = value;
                this.RaisePropertyChanged("Val_Long");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public System.Nullable<bool> Val_Bool {
            get {
                return this.val_BoolField;
            }
            set {
                this.val_BoolField = value;
                this.RaisePropertyChanged("Val_Bool");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<System.DateTime> Val_Date {
            get {
                return this.val_DateField;
            }
            set {
                this.val_DateField = value;
                this.RaisePropertyChanged("Val_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<double> Val_Real {
            get {
                return this.val_RealField;
            }
            set {
                this.val_RealField = value;
                this.RaisePropertyChanged("Val_Real");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Val_String {
            get {
                return this.val_StringField;
            }
            set {
                this.val_StringField = value;
                this.RaisePropertyChanged("Val_String");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public System.Nullable<long> Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("Count");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OServiceClassesSoapChannel : SilverOnt.OServiceClasses.OServiceClassesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfigCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConfigCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverOnt.OServiceClasses.Config[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverOnt.OServiceClasses.Config[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClassesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ClassesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverOnt.OServiceClasses.clsOntologyItem[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverOnt.OServiceClasses.clsOntologyItem[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClassesByGuidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ClassesByGuidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverOnt.OServiceClasses.clsOntologyItem[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverOnt.OServiceClasses.clsOntologyItem[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClassesByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ClassesByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverOnt.OServiceClasses.clsOntologyItem[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverOnt.OServiceClasses.clsOntologyItem[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OServiceClassesSoapClient : System.ServiceModel.ClientBase<SilverOnt.OServiceClasses.OServiceClassesSoap>, SilverOnt.OServiceClasses.OServiceClassesSoap {
        
        private BeginOperationDelegate onBeginConfigDelegate;
        
        private EndOperationDelegate onEndConfigDelegate;
        
        private System.Threading.SendOrPostCallback onConfigCompletedDelegate;
        
        private BeginOperationDelegate onBeginClassesDelegate;
        
        private EndOperationDelegate onEndClassesDelegate;
        
        private System.Threading.SendOrPostCallback onClassesCompletedDelegate;
        
        private BeginOperationDelegate onBeginClassesByGuidDelegate;
        
        private EndOperationDelegate onEndClassesByGuidDelegate;
        
        private System.Threading.SendOrPostCallback onClassesByGuidCompletedDelegate;
        
        private BeginOperationDelegate onBeginClassesByNameDelegate;
        
        private EndOperationDelegate onEndClassesByNameDelegate;
        
        private System.Threading.SendOrPostCallback onClassesByNameCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public OServiceClassesSoapClient() {
        }
        
        public OServiceClassesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OServiceClassesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OServiceClassesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OServiceClassesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Der CookieContainer konnte nicht festgelegt werden. Stellen Sie sicher, dass die " +
                            "Bindung ein HttpCookieContainerBindingElement enthält.");
                }
            }
        }
        
        public event System.EventHandler<ConfigCompletedEventArgs> ConfigCompleted;
        
        public event System.EventHandler<ClassesCompletedEventArgs> ClassesCompleted;
        
        public event System.EventHandler<ClassesByGuidCompletedEventArgs> ClassesByGuidCompleted;
        
        public event System.EventHandler<ClassesByNameCompletedEventArgs> ClassesByNameCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverOnt.OServiceClasses.OServiceClassesSoap.BeginConfig(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConfig(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverOnt.OServiceClasses.Config[] SilverOnt.OServiceClasses.OServiceClassesSoap.EndConfig(System.IAsyncResult result) {
            return base.Channel.EndConfig(result);
        }
        
        private System.IAsyncResult OnBeginConfig(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SilverOnt.OServiceClasses.OServiceClassesSoap)(this)).BeginConfig(callback, asyncState);
        }
        
        private object[] OnEndConfig(System.IAsyncResult result) {
            SilverOnt.OServiceClasses.Config[] retVal = ((SilverOnt.OServiceClasses.OServiceClassesSoap)(this)).EndConfig(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConfigCompleted(object state) {
            if ((this.ConfigCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConfigCompleted(this, new ConfigCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConfigAsync() {
            this.ConfigAsync(null);
        }
        
        public void ConfigAsync(object userState) {
            if ((this.onBeginConfigDelegate == null)) {
                this.onBeginConfigDelegate = new BeginOperationDelegate(this.OnBeginConfig);
            }
            if ((this.onEndConfigDelegate == null)) {
                this.onEndConfigDelegate = new EndOperationDelegate(this.OnEndConfig);
            }
            if ((this.onConfigCompletedDelegate == null)) {
                this.onConfigCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConfigCompleted);
            }
            base.InvokeAsync(this.onBeginConfigDelegate, null, this.onEndConfigDelegate, this.onConfigCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverOnt.OServiceClasses.OServiceClassesSoap.BeginClasses(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginClasses(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverOnt.OServiceClasses.clsOntologyItem[] SilverOnt.OServiceClasses.OServiceClassesSoap.EndClasses(System.IAsyncResult result) {
            return base.Channel.EndClasses(result);
        }
        
        private System.IAsyncResult OnBeginClasses(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SilverOnt.OServiceClasses.OServiceClassesSoap)(this)).BeginClasses(callback, asyncState);
        }
        
        private object[] OnEndClasses(System.IAsyncResult result) {
            SilverOnt.OServiceClasses.clsOntologyItem[] retVal = ((SilverOnt.OServiceClasses.OServiceClassesSoap)(this)).EndClasses(result);
            return new object[] {
                    retVal};
        }
        
        private void OnClassesCompleted(object state) {
            if ((this.ClassesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ClassesCompleted(this, new ClassesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ClassesAsync() {
            this.ClassesAsync(null);
        }
        
        public void ClassesAsync(object userState) {
            if ((this.onBeginClassesDelegate == null)) {
                this.onBeginClassesDelegate = new BeginOperationDelegate(this.OnBeginClasses);
            }
            if ((this.onEndClassesDelegate == null)) {
                this.onEndClassesDelegate = new EndOperationDelegate(this.OnEndClasses);
            }
            if ((this.onClassesCompletedDelegate == null)) {
                this.onClassesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnClassesCompleted);
            }
            base.InvokeAsync(this.onBeginClassesDelegate, null, this.onEndClassesDelegate, this.onClassesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverOnt.OServiceClasses.OServiceClassesSoap.BeginClassesByGuid(string guid, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginClassesByGuid(guid, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverOnt.OServiceClasses.clsOntologyItem[] SilverOnt.OServiceClasses.OServiceClassesSoap.EndClassesByGuid(System.IAsyncResult result) {
            return base.Channel.EndClassesByGuid(result);
        }
        
        private System.IAsyncResult OnBeginClassesByGuid(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string guid = ((string)(inValues[0]));
            return ((SilverOnt.OServiceClasses.OServiceClassesSoap)(this)).BeginClassesByGuid(guid, callback, asyncState);
        }
        
        private object[] OnEndClassesByGuid(System.IAsyncResult result) {
            SilverOnt.OServiceClasses.clsOntologyItem[] retVal = ((SilverOnt.OServiceClasses.OServiceClassesSoap)(this)).EndClassesByGuid(result);
            return new object[] {
                    retVal};
        }
        
        private void OnClassesByGuidCompleted(object state) {
            if ((this.ClassesByGuidCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ClassesByGuidCompleted(this, new ClassesByGuidCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ClassesByGuidAsync(string guid) {
            this.ClassesByGuidAsync(guid, null);
        }
        
        public void ClassesByGuidAsync(string guid, object userState) {
            if ((this.onBeginClassesByGuidDelegate == null)) {
                this.onBeginClassesByGuidDelegate = new BeginOperationDelegate(this.OnBeginClassesByGuid);
            }
            if ((this.onEndClassesByGuidDelegate == null)) {
                this.onEndClassesByGuidDelegate = new EndOperationDelegate(this.OnEndClassesByGuid);
            }
            if ((this.onClassesByGuidCompletedDelegate == null)) {
                this.onClassesByGuidCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnClassesByGuidCompleted);
            }
            base.InvokeAsync(this.onBeginClassesByGuidDelegate, new object[] {
                        guid}, this.onEndClassesByGuidDelegate, this.onClassesByGuidCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverOnt.OServiceClasses.OServiceClassesSoap.BeginClassesByName(string name, bool strict, bool caseSensitive, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginClassesByName(name, strict, caseSensitive, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverOnt.OServiceClasses.clsOntologyItem[] SilverOnt.OServiceClasses.OServiceClassesSoap.EndClassesByName(System.IAsyncResult result) {
            return base.Channel.EndClassesByName(result);
        }
        
        private System.IAsyncResult OnBeginClassesByName(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string name = ((string)(inValues[0]));
            bool strict = ((bool)(inValues[1]));
            bool caseSensitive = ((bool)(inValues[2]));
            return ((SilverOnt.OServiceClasses.OServiceClassesSoap)(this)).BeginClassesByName(name, strict, caseSensitive, callback, asyncState);
        }
        
        private object[] OnEndClassesByName(System.IAsyncResult result) {
            SilverOnt.OServiceClasses.clsOntologyItem[] retVal = ((SilverOnt.OServiceClasses.OServiceClassesSoap)(this)).EndClassesByName(result);
            return new object[] {
                    retVal};
        }
        
        private void OnClassesByNameCompleted(object state) {
            if ((this.ClassesByNameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ClassesByNameCompleted(this, new ClassesByNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ClassesByNameAsync(string name, bool strict, bool caseSensitive) {
            this.ClassesByNameAsync(name, strict, caseSensitive, null);
        }
        
        public void ClassesByNameAsync(string name, bool strict, bool caseSensitive, object userState) {
            if ((this.onBeginClassesByNameDelegate == null)) {
                this.onBeginClassesByNameDelegate = new BeginOperationDelegate(this.OnBeginClassesByName);
            }
            if ((this.onEndClassesByNameDelegate == null)) {
                this.onEndClassesByNameDelegate = new EndOperationDelegate(this.OnEndClassesByName);
            }
            if ((this.onClassesByNameCompletedDelegate == null)) {
                this.onClassesByNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnClassesByNameCompleted);
            }
            base.InvokeAsync(this.onBeginClassesByNameDelegate, new object[] {
                        name,
                        strict,
                        caseSensitive}, this.onEndClassesByNameDelegate, this.onClassesByNameCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SilverOnt.OServiceClasses.OServiceClassesSoap CreateChannel() {
            return new OServiceClassesSoapClientChannel(this);
        }
        
        private class OServiceClassesSoapClientChannel : ChannelBase<SilverOnt.OServiceClasses.OServiceClassesSoap>, SilverOnt.OServiceClasses.OServiceClassesSoap {
            
            public OServiceClassesSoapClientChannel(System.ServiceModel.ClientBase<SilverOnt.OServiceClasses.OServiceClassesSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginConfig(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Config", _args, callback, asyncState);
                return _result;
            }
            
            public SilverOnt.OServiceClasses.Config[] EndConfig(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverOnt.OServiceClasses.Config[] _result = ((SilverOnt.OServiceClasses.Config[])(base.EndInvoke("Config", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginClasses(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Classes", _args, callback, asyncState);
                return _result;
            }
            
            public SilverOnt.OServiceClasses.clsOntologyItem[] EndClasses(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverOnt.OServiceClasses.clsOntologyItem[] _result = ((SilverOnt.OServiceClasses.clsOntologyItem[])(base.EndInvoke("Classes", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginClassesByGuid(string guid, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = guid;
                System.IAsyncResult _result = base.BeginInvoke("ClassesByGuid", _args, callback, asyncState);
                return _result;
            }
            
            public SilverOnt.OServiceClasses.clsOntologyItem[] EndClassesByGuid(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverOnt.OServiceClasses.clsOntologyItem[] _result = ((SilverOnt.OServiceClasses.clsOntologyItem[])(base.EndInvoke("ClassesByGuid", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginClassesByName(string name, bool strict, bool caseSensitive, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = name;
                _args[1] = strict;
                _args[2] = caseSensitive;
                System.IAsyncResult _result = base.BeginInvoke("ClassesByName", _args, callback, asyncState);
                return _result;
            }
            
            public SilverOnt.OServiceClasses.clsOntologyItem[] EndClassesByName(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverOnt.OServiceClasses.clsOntologyItem[] _result = ((SilverOnt.OServiceClasses.clsOntologyItem[])(base.EndInvoke("ClassesByName", _args, result)));
                return _result;
            }
        }
    }
}
