C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe C:\Users\tassilok\Documents\GitHub\OntologyManagement\Appointment-Module\Appointment-Module.sln
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe C:\Users\tassilok\Documents\GitHub\OntologyManagement\Bill-Module\Bill-Module.sln
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe C:\Users\tassilok\Documents\GitHub\OntologyManagement\Change-Module\Change-Module.sln
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe C:\Users\tassilok\Documents\GitHub\OntologyManagement\Development-Module\Development-Module.sln
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe C:\Users\tassilok\Documents\GitHub\OntologyManagement\EsMaintenance\EsMaintenance.exe
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe C:\Users\tassilok\Documents\GitHub\OntologyManagement\Filesystem-Module\Filesystem-Module.exe
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe C:\Users\tassilok\Documents\GitHub\OntologyManagement\GraphMLConnector\GraphMLConnector.sln
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe C:\Users\tassilok\Documents\GitHub\OntologyManagement\Log-Module\Log-Module.sln
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe C:\Users\tassilok\Documents\GitHub\OntologyManagement\Media-Viewer-Module\Media-Viewer-Module.sln
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe C:\Users\tassilok\Documents\GitHub\OntologyManagement\Office-Module\Office-Module.sln
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe C:\Users\tassilok\Documents\GitHub\OntologyManagement\Ontolog-Module\Ontolog-Module.sln
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe C:\Users\tassilok\Documents\GitHub\OntologyManagement\Partner-Module\Partner-Module.sln
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe C:\Users\tassilok\Documents\GitHub\OntologyManagement\Process-Module\Process-Module.sln
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe C:\Users\tassilok\Documents\GitHub\OntologyManagement\Report-Module\Report-Module.sln
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe C:\Users\tassilok\Documents\GitHub\OntologyManagement\Scenes-Literatur-Module\Scenes-Literatur-Module.sln
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe C:\Users\tassilok\Documents\GitHub\OntologyManagement\Security-Module\Security-Module.sln
