//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfOnt.OServiceClassAtt {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfClsObjectAtt", Namespace="http://tempuri.org/", ItemName="clsObjectAtt")]
    [System.SerializableAttribute()]
    public class ArrayOfClsObjectAtt : System.Collections.Generic.List<WpfOnt.OServiceClassAtt.clsObjectAtt> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsObjectAtt", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class clsObjectAtt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_AttributeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_AttributeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Name_AttributeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_ObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Name_ObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_ClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Name_ClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Val_NamedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Val_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_DataTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Name_DataTypeField;
        
        private System.Nullable<bool> Val_BoolField;
        
        private System.Nullable<bool> Val_BitField;
        
        private System.Nullable<long> Val_IntField;
        
        private System.Nullable<long> Val_LngField;
        
        private System.Nullable<System.DateTime> Val_DatetimeField;
        
        private System.Nullable<double> Val_RealField;
        
        private System.Nullable<double> Val_DoubleField;
        
        private System.Nullable<System.DateTime> Val_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Val_StringField;
        
        private System.Nullable<long> OrderIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID_Attribute {
            get {
                return this.ID_AttributeField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_AttributeField, value) != true)) {
                    this.ID_AttributeField = value;
                    this.RaisePropertyChanged("ID_Attribute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID_AttributeType {
            get {
                return this.ID_AttributeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_AttributeTypeField, value) != true)) {
                    this.ID_AttributeTypeField = value;
                    this.RaisePropertyChanged("ID_AttributeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name_AttributeType {
            get {
                return this.Name_AttributeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Name_AttributeTypeField, value) != true)) {
                    this.Name_AttributeTypeField = value;
                    this.RaisePropertyChanged("Name_AttributeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ID_Object {
            get {
                return this.ID_ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_ObjectField, value) != true)) {
                    this.ID_ObjectField = value;
                    this.RaisePropertyChanged("ID_Object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Name_Object {
            get {
                return this.Name_ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.Name_ObjectField, value) != true)) {
                    this.Name_ObjectField = value;
                    this.RaisePropertyChanged("Name_Object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ID_Class {
            get {
                return this.ID_ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_ClassField, value) != true)) {
                    this.ID_ClassField = value;
                    this.RaisePropertyChanged("ID_Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Name_Class {
            get {
                return this.Name_ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.Name_ClassField, value) != true)) {
                    this.Name_ClassField = value;
                    this.RaisePropertyChanged("Name_Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Val_Named {
            get {
                return this.Val_NamedField;
            }
            set {
                if ((object.ReferenceEquals(this.Val_NamedField, value) != true)) {
                    this.Val_NamedField = value;
                    this.RaisePropertyChanged("Val_Named");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Val_Name {
            get {
                return this.Val_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Val_NameField, value) != true)) {
                    this.Val_NameField = value;
                    this.RaisePropertyChanged("Val_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ID_DataType {
            get {
                return this.ID_DataTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_DataTypeField, value) != true)) {
                    this.ID_DataTypeField = value;
                    this.RaisePropertyChanged("ID_DataType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Name_DataType {
            get {
                return this.Name_DataTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Name_DataTypeField, value) != true)) {
                    this.Name_DataTypeField = value;
                    this.RaisePropertyChanged("Name_DataType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<bool> Val_Bool {
            get {
                return this.Val_BoolField;
            }
            set {
                if ((this.Val_BoolField.Equals(value) != true)) {
                    this.Val_BoolField = value;
                    this.RaisePropertyChanged("Val_Bool");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.Nullable<bool> Val_Bit {
            get {
                return this.Val_BitField;
            }
            set {
                if ((this.Val_BitField.Equals(value) != true)) {
                    this.Val_BitField = value;
                    this.RaisePropertyChanged("Val_Bit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public System.Nullable<long> Val_Int {
            get {
                return this.Val_IntField;
            }
            set {
                if ((this.Val_IntField.Equals(value) != true)) {
                    this.Val_IntField = value;
                    this.RaisePropertyChanged("Val_Int");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.Nullable<long> Val_Lng {
            get {
                return this.Val_LngField;
            }
            set {
                if ((this.Val_LngField.Equals(value) != true)) {
                    this.Val_LngField = value;
                    this.RaisePropertyChanged("Val_Lng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public System.Nullable<System.DateTime> Val_Datetime {
            get {
                return this.Val_DatetimeField;
            }
            set {
                if ((this.Val_DatetimeField.Equals(value) != true)) {
                    this.Val_DatetimeField = value;
                    this.RaisePropertyChanged("Val_Datetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public System.Nullable<double> Val_Real {
            get {
                return this.Val_RealField;
            }
            set {
                if ((this.Val_RealField.Equals(value) != true)) {
                    this.Val_RealField = value;
                    this.RaisePropertyChanged("Val_Real");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public System.Nullable<double> Val_Double {
            get {
                return this.Val_DoubleField;
            }
            set {
                if ((this.Val_DoubleField.Equals(value) != true)) {
                    this.Val_DoubleField = value;
                    this.RaisePropertyChanged("Val_Double");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public System.Nullable<System.DateTime> Val_Date {
            get {
                return this.Val_DateField;
            }
            set {
                if ((this.Val_DateField.Equals(value) != true)) {
                    this.Val_DateField = value;
                    this.RaisePropertyChanged("Val_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string Val_String {
            get {
                return this.Val_StringField;
            }
            set {
                if ((object.ReferenceEquals(this.Val_StringField, value) != true)) {
                    this.Val_StringField = value;
                    this.RaisePropertyChanged("Val_String");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public System.Nullable<long> OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfClsClassAtt", Namespace="http://tempuri.org/", ItemName="clsClassAtt")]
    [System.SerializableAttribute()]
    public class ArrayOfClsClassAtt : System.Collections.Generic.List<WpfOnt.OServiceClassAtt.clsClassAtt> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsClassAtt", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class clsClassAtt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_ClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Name_ClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_AttributeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Name_AttributeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_DataTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Name_DataTypeField;
        
        private System.Nullable<long> MinField;
        
        private System.Nullable<long> MaxField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID_Class {
            get {
                return this.ID_ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_ClassField, value) != true)) {
                    this.ID_ClassField = value;
                    this.RaisePropertyChanged("ID_Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name_Class {
            get {
                return this.Name_ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.Name_ClassField, value) != true)) {
                    this.Name_ClassField = value;
                    this.RaisePropertyChanged("Name_Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ID_AttributeType {
            get {
                return this.ID_AttributeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_AttributeTypeField, value) != true)) {
                    this.ID_AttributeTypeField = value;
                    this.RaisePropertyChanged("ID_AttributeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Name_AttributeType {
            get {
                return this.Name_AttributeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Name_AttributeTypeField, value) != true)) {
                    this.Name_AttributeTypeField = value;
                    this.RaisePropertyChanged("Name_AttributeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ID_DataType {
            get {
                return this.ID_DataTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_DataTypeField, value) != true)) {
                    this.ID_DataTypeField = value;
                    this.RaisePropertyChanged("ID_DataType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Name_DataType {
            get {
                return this.Name_DataTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Name_DataTypeField, value) != true)) {
                    this.Name_DataTypeField = value;
                    this.RaisePropertyChanged("Name_DataType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<long> Min {
            get {
                return this.MinField;
            }
            set {
                if ((this.MinField.Equals(value) != true)) {
                    this.MinField = value;
                    this.RaisePropertyChanged("Min");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<long> Max {
            get {
                return this.MaxField;
            }
            set {
                if ((this.MaxField.Equals(value) != true)) {
                    this.MaxField = value;
                    this.RaisePropertyChanged("Max");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OServiceClassAtt.OServiceClassAttSoap")]
    public interface OServiceClassAttSoap {
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname ObjectAttsResult aus Namespace http://tempuri.org/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObjectAtts", ReplyAction="*")]
        WpfOnt.OServiceClassAtt.ObjectAttsResponse ObjectAtts(WpfOnt.OServiceClassAtt.ObjectAttsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObjectAtts", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.ObjectAttsResponse> ObjectAttsAsync(WpfOnt.OServiceClassAtt.ObjectAttsRequest request);
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname ClassAttributesResult aus Namespace http://tempuri.org/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClassAttributes", ReplyAction="*")]
        WpfOnt.OServiceClassAtt.ClassAttributesResponse ClassAttributes(WpfOnt.OServiceClassAtt.ClassAttributesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClassAttributes", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.ClassAttributesResponse> ClassAttributesAsync(WpfOnt.OServiceClassAtt.ClassAttributesRequest request);
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname guidClass aus Namespace http://tempuri.org/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClassAttributesByClassGuid", ReplyAction="*")]
        WpfOnt.OServiceClassAtt.ClassAttributesByClassGuidResponse ClassAttributesByClassGuid(WpfOnt.OServiceClassAtt.ClassAttributesByClassGuidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClassAttributesByClassGuid", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.ClassAttributesByClassGuidResponse> ClassAttributesByClassGuidAsync(WpfOnt.OServiceClassAtt.ClassAttributesByClassGuidRequest request);
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname guidAttributeType aus Namespace http://tempuri.org/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClassAttributesByAttributeTypeGuid", ReplyAction="*")]
        WpfOnt.OServiceClassAtt.ClassAttributesByAttributeTypeGuidResponse ClassAttributesByAttributeTypeGuid(WpfOnt.OServiceClassAtt.ClassAttributesByAttributeTypeGuidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClassAttributesByAttributeTypeGuid", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.ClassAttributesByAttributeTypeGuidResponse> ClassAttributesByAttributeTypeGuidAsync(WpfOnt.OServiceClassAtt.ClassAttributesByAttributeTypeGuidRequest request);
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname guidAttributeType aus Namespace http://tempuri.org/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClassAttributesByClassGuid_ttributeTypeGuid", ReplyAction="*")]
        WpfOnt.OServiceClassAtt.ClassAttributesByClassGuid_ttributeTypeGuidResponse ClassAttributesByClassGuid_ttributeTypeGuid(WpfOnt.OServiceClassAtt.ClassAttributesByClassGuid_ttributeTypeGuidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClassAttributesByClassGuid_ttributeTypeGuid", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.ClassAttributesByClassGuid_ttributeTypeGuidResponse> ClassAttributesByClassGuid_ttributeTypeGuidAsync(WpfOnt.OServiceClassAtt.ClassAttributesByClassGuid_ttributeTypeGuidRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObjectAttsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObjectAtts", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceClassAtt.ObjectAttsRequestBody Body;
        
        public ObjectAttsRequest() {
        }
        
        public ObjectAttsRequest(WpfOnt.OServiceClassAtt.ObjectAttsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectAttsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool onlyIds;
        
        public ObjectAttsRequestBody() {
        }
        
        public ObjectAttsRequestBody(bool onlyIds) {
            this.onlyIds = onlyIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObjectAttsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObjectAttsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceClassAtt.ObjectAttsResponseBody Body;
        
        public ObjectAttsResponse() {
        }
        
        public ObjectAttsResponse(WpfOnt.OServiceClassAtt.ObjectAttsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectAttsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfOnt.OServiceClassAtt.ArrayOfClsObjectAtt ObjectAttsResult;
        
        public ObjectAttsResponseBody() {
        }
        
        public ObjectAttsResponseBody(WpfOnt.OServiceClassAtt.ArrayOfClsObjectAtt ObjectAttsResult) {
            this.ObjectAttsResult = ObjectAttsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClassAttributesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClassAttributes", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceClassAtt.ClassAttributesRequestBody Body;
        
        public ClassAttributesRequest() {
        }
        
        public ClassAttributesRequest(WpfOnt.OServiceClassAtt.ClassAttributesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClassAttributesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool onlyIds;
        
        public ClassAttributesRequestBody() {
        }
        
        public ClassAttributesRequestBody(bool onlyIds) {
            this.onlyIds = onlyIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClassAttributesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClassAttributesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceClassAtt.ClassAttributesResponseBody Body;
        
        public ClassAttributesResponse() {
        }
        
        public ClassAttributesResponse(WpfOnt.OServiceClassAtt.ClassAttributesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClassAttributesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfOnt.OServiceClassAtt.ArrayOfClsClassAtt ClassAttributesResult;
        
        public ClassAttributesResponseBody() {
        }
        
        public ClassAttributesResponseBody(WpfOnt.OServiceClassAtt.ArrayOfClsClassAtt ClassAttributesResult) {
            this.ClassAttributesResult = ClassAttributesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClassAttributesByClassGuidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClassAttributesByClassGuid", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceClassAtt.ClassAttributesByClassGuidRequestBody Body;
        
        public ClassAttributesByClassGuidRequest() {
        }
        
        public ClassAttributesByClassGuidRequest(WpfOnt.OServiceClassAtt.ClassAttributesByClassGuidRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClassAttributesByClassGuidRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string guidClass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool onlyIds;
        
        public ClassAttributesByClassGuidRequestBody() {
        }
        
        public ClassAttributesByClassGuidRequestBody(string guidClass, bool onlyIds) {
            this.guidClass = guidClass;
            this.onlyIds = onlyIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClassAttributesByClassGuidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClassAttributesByClassGuidResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceClassAtt.ClassAttributesByClassGuidResponseBody Body;
        
        public ClassAttributesByClassGuidResponse() {
        }
        
        public ClassAttributesByClassGuidResponse(WpfOnt.OServiceClassAtt.ClassAttributesByClassGuidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClassAttributesByClassGuidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfOnt.OServiceClassAtt.ArrayOfClsClassAtt ClassAttributesByClassGuidResult;
        
        public ClassAttributesByClassGuidResponseBody() {
        }
        
        public ClassAttributesByClassGuidResponseBody(WpfOnt.OServiceClassAtt.ArrayOfClsClassAtt ClassAttributesByClassGuidResult) {
            this.ClassAttributesByClassGuidResult = ClassAttributesByClassGuidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClassAttributesByAttributeTypeGuidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClassAttributesByAttributeTypeGuid", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceClassAtt.ClassAttributesByAttributeTypeGuidRequestBody Body;
        
        public ClassAttributesByAttributeTypeGuidRequest() {
        }
        
        public ClassAttributesByAttributeTypeGuidRequest(WpfOnt.OServiceClassAtt.ClassAttributesByAttributeTypeGuidRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClassAttributesByAttributeTypeGuidRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string guidAttributeType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool onlyIds;
        
        public ClassAttributesByAttributeTypeGuidRequestBody() {
        }
        
        public ClassAttributesByAttributeTypeGuidRequestBody(string guidAttributeType, bool onlyIds) {
            this.guidAttributeType = guidAttributeType;
            this.onlyIds = onlyIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClassAttributesByAttributeTypeGuidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClassAttributesByAttributeTypeGuidResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceClassAtt.ClassAttributesByAttributeTypeGuidResponseBody Body;
        
        public ClassAttributesByAttributeTypeGuidResponse() {
        }
        
        public ClassAttributesByAttributeTypeGuidResponse(WpfOnt.OServiceClassAtt.ClassAttributesByAttributeTypeGuidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClassAttributesByAttributeTypeGuidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfOnt.OServiceClassAtt.ArrayOfClsClassAtt ClassAttributesByAttributeTypeGuidResult;
        
        public ClassAttributesByAttributeTypeGuidResponseBody() {
        }
        
        public ClassAttributesByAttributeTypeGuidResponseBody(WpfOnt.OServiceClassAtt.ArrayOfClsClassAtt ClassAttributesByAttributeTypeGuidResult) {
            this.ClassAttributesByAttributeTypeGuidResult = ClassAttributesByAttributeTypeGuidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClassAttributesByClassGuid_ttributeTypeGuidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClassAttributesByClassGuid_ttributeTypeGuid", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceClassAtt.ClassAttributesByClassGuid_ttributeTypeGuidRequestBody Body;
        
        public ClassAttributesByClassGuid_ttributeTypeGuidRequest() {
        }
        
        public ClassAttributesByClassGuid_ttributeTypeGuidRequest(WpfOnt.OServiceClassAtt.ClassAttributesByClassGuid_ttributeTypeGuidRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClassAttributesByClassGuid_ttributeTypeGuidRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string guidAttributeType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string guidClass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool onlyIds;
        
        public ClassAttributesByClassGuid_ttributeTypeGuidRequestBody() {
        }
        
        public ClassAttributesByClassGuid_ttributeTypeGuidRequestBody(string guidAttributeType, string guidClass, bool onlyIds) {
            this.guidAttributeType = guidAttributeType;
            this.guidClass = guidClass;
            this.onlyIds = onlyIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClassAttributesByClassGuid_ttributeTypeGuidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClassAttributesByClassGuid_ttributeTypeGuidResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceClassAtt.ClassAttributesByClassGuid_ttributeTypeGuidResponseBody Body;
        
        public ClassAttributesByClassGuid_ttributeTypeGuidResponse() {
        }
        
        public ClassAttributesByClassGuid_ttributeTypeGuidResponse(WpfOnt.OServiceClassAtt.ClassAttributesByClassGuid_ttributeTypeGuidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClassAttributesByClassGuid_ttributeTypeGuidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfOnt.OServiceClassAtt.ArrayOfClsClassAtt ClassAttributesByClassGuid_ttributeTypeGuidResult;
        
        public ClassAttributesByClassGuid_ttributeTypeGuidResponseBody() {
        }
        
        public ClassAttributesByClassGuid_ttributeTypeGuidResponseBody(WpfOnt.OServiceClassAtt.ArrayOfClsClassAtt ClassAttributesByClassGuid_ttributeTypeGuidResult) {
            this.ClassAttributesByClassGuid_ttributeTypeGuidResult = ClassAttributesByClassGuid_ttributeTypeGuidResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OServiceClassAttSoapChannel : WpfOnt.OServiceClassAtt.OServiceClassAttSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OServiceClassAttSoapClient : System.ServiceModel.ClientBase<WpfOnt.OServiceClassAtt.OServiceClassAttSoap>, WpfOnt.OServiceClassAtt.OServiceClassAttSoap {
        
        public OServiceClassAttSoapClient() {
        }
        
        public OServiceClassAttSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OServiceClassAttSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OServiceClassAttSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OServiceClassAttSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfOnt.OServiceClassAtt.ObjectAttsResponse WpfOnt.OServiceClassAtt.OServiceClassAttSoap.ObjectAtts(WpfOnt.OServiceClassAtt.ObjectAttsRequest request) {
            return base.Channel.ObjectAtts(request);
        }
        
        public WpfOnt.OServiceClassAtt.ArrayOfClsObjectAtt ObjectAtts(bool onlyIds) {
            WpfOnt.OServiceClassAtt.ObjectAttsRequest inValue = new WpfOnt.OServiceClassAtt.ObjectAttsRequest();
            inValue.Body = new WpfOnt.OServiceClassAtt.ObjectAttsRequestBody();
            inValue.Body.onlyIds = onlyIds;
            WpfOnt.OServiceClassAtt.ObjectAttsResponse retVal = ((WpfOnt.OServiceClassAtt.OServiceClassAttSoap)(this)).ObjectAtts(inValue);
            return retVal.Body.ObjectAttsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.ObjectAttsResponse> WpfOnt.OServiceClassAtt.OServiceClassAttSoap.ObjectAttsAsync(WpfOnt.OServiceClassAtt.ObjectAttsRequest request) {
            return base.Channel.ObjectAttsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.ObjectAttsResponse> ObjectAttsAsync(bool onlyIds) {
            WpfOnt.OServiceClassAtt.ObjectAttsRequest inValue = new WpfOnt.OServiceClassAtt.ObjectAttsRequest();
            inValue.Body = new WpfOnt.OServiceClassAtt.ObjectAttsRequestBody();
            inValue.Body.onlyIds = onlyIds;
            return ((WpfOnt.OServiceClassAtt.OServiceClassAttSoap)(this)).ObjectAttsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfOnt.OServiceClassAtt.ClassAttributesResponse WpfOnt.OServiceClassAtt.OServiceClassAttSoap.ClassAttributes(WpfOnt.OServiceClassAtt.ClassAttributesRequest request) {
            return base.Channel.ClassAttributes(request);
        }
        
        public WpfOnt.OServiceClassAtt.ArrayOfClsClassAtt ClassAttributes(bool onlyIds) {
            WpfOnt.OServiceClassAtt.ClassAttributesRequest inValue = new WpfOnt.OServiceClassAtt.ClassAttributesRequest();
            inValue.Body = new WpfOnt.OServiceClassAtt.ClassAttributesRequestBody();
            inValue.Body.onlyIds = onlyIds;
            WpfOnt.OServiceClassAtt.ClassAttributesResponse retVal = ((WpfOnt.OServiceClassAtt.OServiceClassAttSoap)(this)).ClassAttributes(inValue);
            return retVal.Body.ClassAttributesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.ClassAttributesResponse> WpfOnt.OServiceClassAtt.OServiceClassAttSoap.ClassAttributesAsync(WpfOnt.OServiceClassAtt.ClassAttributesRequest request) {
            return base.Channel.ClassAttributesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.ClassAttributesResponse> ClassAttributesAsync(bool onlyIds) {
            WpfOnt.OServiceClassAtt.ClassAttributesRequest inValue = new WpfOnt.OServiceClassAtt.ClassAttributesRequest();
            inValue.Body = new WpfOnt.OServiceClassAtt.ClassAttributesRequestBody();
            inValue.Body.onlyIds = onlyIds;
            return ((WpfOnt.OServiceClassAtt.OServiceClassAttSoap)(this)).ClassAttributesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfOnt.OServiceClassAtt.ClassAttributesByClassGuidResponse WpfOnt.OServiceClassAtt.OServiceClassAttSoap.ClassAttributesByClassGuid(WpfOnt.OServiceClassAtt.ClassAttributesByClassGuidRequest request) {
            return base.Channel.ClassAttributesByClassGuid(request);
        }
        
        public WpfOnt.OServiceClassAtt.ArrayOfClsClassAtt ClassAttributesByClassGuid(string guidClass, bool onlyIds) {
            WpfOnt.OServiceClassAtt.ClassAttributesByClassGuidRequest inValue = new WpfOnt.OServiceClassAtt.ClassAttributesByClassGuidRequest();
            inValue.Body = new WpfOnt.OServiceClassAtt.ClassAttributesByClassGuidRequestBody();
            inValue.Body.guidClass = guidClass;
            inValue.Body.onlyIds = onlyIds;
            WpfOnt.OServiceClassAtt.ClassAttributesByClassGuidResponse retVal = ((WpfOnt.OServiceClassAtt.OServiceClassAttSoap)(this)).ClassAttributesByClassGuid(inValue);
            return retVal.Body.ClassAttributesByClassGuidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.ClassAttributesByClassGuidResponse> WpfOnt.OServiceClassAtt.OServiceClassAttSoap.ClassAttributesByClassGuidAsync(WpfOnt.OServiceClassAtt.ClassAttributesByClassGuidRequest request) {
            return base.Channel.ClassAttributesByClassGuidAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.ClassAttributesByClassGuidResponse> ClassAttributesByClassGuidAsync(string guidClass, bool onlyIds) {
            WpfOnt.OServiceClassAtt.ClassAttributesByClassGuidRequest inValue = new WpfOnt.OServiceClassAtt.ClassAttributesByClassGuidRequest();
            inValue.Body = new WpfOnt.OServiceClassAtt.ClassAttributesByClassGuidRequestBody();
            inValue.Body.guidClass = guidClass;
            inValue.Body.onlyIds = onlyIds;
            return ((WpfOnt.OServiceClassAtt.OServiceClassAttSoap)(this)).ClassAttributesByClassGuidAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfOnt.OServiceClassAtt.ClassAttributesByAttributeTypeGuidResponse WpfOnt.OServiceClassAtt.OServiceClassAttSoap.ClassAttributesByAttributeTypeGuid(WpfOnt.OServiceClassAtt.ClassAttributesByAttributeTypeGuidRequest request) {
            return base.Channel.ClassAttributesByAttributeTypeGuid(request);
        }
        
        public WpfOnt.OServiceClassAtt.ArrayOfClsClassAtt ClassAttributesByAttributeTypeGuid(string guidAttributeType, bool onlyIds) {
            WpfOnt.OServiceClassAtt.ClassAttributesByAttributeTypeGuidRequest inValue = new WpfOnt.OServiceClassAtt.ClassAttributesByAttributeTypeGuidRequest();
            inValue.Body = new WpfOnt.OServiceClassAtt.ClassAttributesByAttributeTypeGuidRequestBody();
            inValue.Body.guidAttributeType = guidAttributeType;
            inValue.Body.onlyIds = onlyIds;
            WpfOnt.OServiceClassAtt.ClassAttributesByAttributeTypeGuidResponse retVal = ((WpfOnt.OServiceClassAtt.OServiceClassAttSoap)(this)).ClassAttributesByAttributeTypeGuid(inValue);
            return retVal.Body.ClassAttributesByAttributeTypeGuidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.ClassAttributesByAttributeTypeGuidResponse> WpfOnt.OServiceClassAtt.OServiceClassAttSoap.ClassAttributesByAttributeTypeGuidAsync(WpfOnt.OServiceClassAtt.ClassAttributesByAttributeTypeGuidRequest request) {
            return base.Channel.ClassAttributesByAttributeTypeGuidAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.ClassAttributesByAttributeTypeGuidResponse> ClassAttributesByAttributeTypeGuidAsync(string guidAttributeType, bool onlyIds) {
            WpfOnt.OServiceClassAtt.ClassAttributesByAttributeTypeGuidRequest inValue = new WpfOnt.OServiceClassAtt.ClassAttributesByAttributeTypeGuidRequest();
            inValue.Body = new WpfOnt.OServiceClassAtt.ClassAttributesByAttributeTypeGuidRequestBody();
            inValue.Body.guidAttributeType = guidAttributeType;
            inValue.Body.onlyIds = onlyIds;
            return ((WpfOnt.OServiceClassAtt.OServiceClassAttSoap)(this)).ClassAttributesByAttributeTypeGuidAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfOnt.OServiceClassAtt.ClassAttributesByClassGuid_ttributeTypeGuidResponse WpfOnt.OServiceClassAtt.OServiceClassAttSoap.ClassAttributesByClassGuid_ttributeTypeGuid(WpfOnt.OServiceClassAtt.ClassAttributesByClassGuid_ttributeTypeGuidRequest request) {
            return base.Channel.ClassAttributesByClassGuid_ttributeTypeGuid(request);
        }
        
        public WpfOnt.OServiceClassAtt.ArrayOfClsClassAtt ClassAttributesByClassGuid_ttributeTypeGuid(string guidAttributeType, string guidClass, bool onlyIds) {
            WpfOnt.OServiceClassAtt.ClassAttributesByClassGuid_ttributeTypeGuidRequest inValue = new WpfOnt.OServiceClassAtt.ClassAttributesByClassGuid_ttributeTypeGuidRequest();
            inValue.Body = new WpfOnt.OServiceClassAtt.ClassAttributesByClassGuid_ttributeTypeGuidRequestBody();
            inValue.Body.guidAttributeType = guidAttributeType;
            inValue.Body.guidClass = guidClass;
            inValue.Body.onlyIds = onlyIds;
            WpfOnt.OServiceClassAtt.ClassAttributesByClassGuid_ttributeTypeGuidResponse retVal = ((WpfOnt.OServiceClassAtt.OServiceClassAttSoap)(this)).ClassAttributesByClassGuid_ttributeTypeGuid(inValue);
            return retVal.Body.ClassAttributesByClassGuid_ttributeTypeGuidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.ClassAttributesByClassGuid_ttributeTypeGuidResponse> WpfOnt.OServiceClassAtt.OServiceClassAttSoap.ClassAttributesByClassGuid_ttributeTypeGuidAsync(WpfOnt.OServiceClassAtt.ClassAttributesByClassGuid_ttributeTypeGuidRequest request) {
            return base.Channel.ClassAttributesByClassGuid_ttributeTypeGuidAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.ClassAttributesByClassGuid_ttributeTypeGuidResponse> ClassAttributesByClassGuid_ttributeTypeGuidAsync(string guidAttributeType, string guidClass, bool onlyIds) {
            WpfOnt.OServiceClassAtt.ClassAttributesByClassGuid_ttributeTypeGuidRequest inValue = new WpfOnt.OServiceClassAtt.ClassAttributesByClassGuid_ttributeTypeGuidRequest();
            inValue.Body = new WpfOnt.OServiceClassAtt.ClassAttributesByClassGuid_ttributeTypeGuidRequestBody();
            inValue.Body.guidAttributeType = guidAttributeType;
            inValue.Body.guidClass = guidClass;
            inValue.Body.onlyIds = onlyIds;
            return ((WpfOnt.OServiceClassAtt.OServiceClassAttSoap)(this)).ClassAttributesByClassGuid_ttributeTypeGuidAsync(inValue);
        }
    }
}
