//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfOnt.OServiceClassAtt {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OServiceClassAtt.OServiceClassAttSoap")]
    public interface OServiceClassAttSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Config", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfOnt.OServiceClassAtt.Config[] Config();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Config", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.Config[]> ConfigAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObjectAtts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfOnt.OServiceClassAtt.clsObjectAtt[] ObjectAtts(bool onlyIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObjectAtts", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.clsObjectAtt[]> ObjectAttsAsync(bool onlyIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClassAttributes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfOnt.OServiceClassAtt.clsClassAtt[] ClassAttributes(bool onlyIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClassAttributes", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.clsClassAtt[]> ClassAttributesAsync(bool onlyIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClassAttributesByClassGuid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfOnt.OServiceClassAtt.clsClassAtt[] ClassAttributesByClassGuid(string guidClass, bool onlyIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClassAttributesByClassGuid", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.clsClassAtt[]> ClassAttributesByClassGuidAsync(string guidClass, bool onlyIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClassAttributesByAttributeTypeGuid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfOnt.OServiceClassAtt.clsClassAtt[] ClassAttributesByAttributeTypeGuid(string guidAttributeType, bool onlyIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClassAttributesByAttributeTypeGuid", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.clsClassAtt[]> ClassAttributesByAttributeTypeGuidAsync(string guidAttributeType, bool onlyIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClassAttributesByClassGuid_ttributeTypeGuid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfOnt.OServiceClassAtt.clsClassAtt[] ClassAttributesByClassGuid_ttributeTypeGuid(string guidAttributeType, string guidClass, bool onlyIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClassAttributesByClassGuid_ttributeTypeGuid", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.clsClassAtt[]> ClassAttributesByClassGuid_ttributeTypeGuidAsync(string guidAttributeType, string guidClass, bool onlyIds);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Config : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string configItemField;
        
        private string configValueStringField;
        
        private int configValueIntField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ConfigItem {
            get {
                return this.configItemField;
            }
            set {
                this.configItemField = value;
                this.RaisePropertyChanged("ConfigItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ConfigValueString {
            get {
                return this.configValueStringField;
            }
            set {
                this.configValueStringField = value;
                this.RaisePropertyChanged("ConfigValueString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ConfigValueInt {
            get {
                return this.configValueIntField;
            }
            set {
                this.configValueIntField = value;
                this.RaisePropertyChanged("ConfigValueInt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsClassAtt : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iD_ClassField;
        
        private string name_ClassField;
        
        private string iD_AttributeTypeField;
        
        private string name_AttributeTypeField;
        
        private string iD_DataTypeField;
        
        private string name_DataTypeField;
        
        private System.Nullable<long> minField;
        
        private System.Nullable<long> maxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID_Class {
            get {
                return this.iD_ClassField;
            }
            set {
                this.iD_ClassField = value;
                this.RaisePropertyChanged("ID_Class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name_Class {
            get {
                return this.name_ClassField;
            }
            set {
                this.name_ClassField = value;
                this.RaisePropertyChanged("Name_Class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ID_AttributeType {
            get {
                return this.iD_AttributeTypeField;
            }
            set {
                this.iD_AttributeTypeField = value;
                this.RaisePropertyChanged("ID_AttributeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name_AttributeType {
            get {
                return this.name_AttributeTypeField;
            }
            set {
                this.name_AttributeTypeField = value;
                this.RaisePropertyChanged("Name_AttributeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ID_DataType {
            get {
                return this.iD_DataTypeField;
            }
            set {
                this.iD_DataTypeField = value;
                this.RaisePropertyChanged("ID_DataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Name_DataType {
            get {
                return this.name_DataTypeField;
            }
            set {
                this.name_DataTypeField = value;
                this.RaisePropertyChanged("Name_DataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<long> Min {
            get {
                return this.minField;
            }
            set {
                this.minField = value;
                this.RaisePropertyChanged("Min");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<long> Max {
            get {
                return this.maxField;
            }
            set {
                this.maxField = value;
                this.RaisePropertyChanged("Max");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsObjectAtt : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iD_AttributeField;
        
        private string iD_AttributeTypeField;
        
        private string name_AttributeTypeField;
        
        private string iD_ObjectField;
        
        private string name_ObjectField;
        
        private string iD_ClassField;
        
        private string name_ClassField;
        
        private string val_NamedField;
        
        private string val_NameField;
        
        private string iD_DataTypeField;
        
        private string name_DataTypeField;
        
        private System.Nullable<bool> val_BoolField;
        
        private System.Nullable<bool> val_BitField;
        
        private System.Nullable<long> val_IntField;
        
        private System.Nullable<long> val_LngField;
        
        private System.Nullable<System.DateTime> val_DatetimeField;
        
        private System.Nullable<double> val_RealField;
        
        private System.Nullable<double> val_DoubleField;
        
        private System.Nullable<System.DateTime> val_DateField;
        
        private string val_StringField;
        
        private System.Nullable<long> orderIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID_Attribute {
            get {
                return this.iD_AttributeField;
            }
            set {
                this.iD_AttributeField = value;
                this.RaisePropertyChanged("ID_Attribute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ID_AttributeType {
            get {
                return this.iD_AttributeTypeField;
            }
            set {
                this.iD_AttributeTypeField = value;
                this.RaisePropertyChanged("ID_AttributeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name_AttributeType {
            get {
                return this.name_AttributeTypeField;
            }
            set {
                this.name_AttributeTypeField = value;
                this.RaisePropertyChanged("Name_AttributeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ID_Object {
            get {
                return this.iD_ObjectField;
            }
            set {
                this.iD_ObjectField = value;
                this.RaisePropertyChanged("ID_Object");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Name_Object {
            get {
                return this.name_ObjectField;
            }
            set {
                this.name_ObjectField = value;
                this.RaisePropertyChanged("Name_Object");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ID_Class {
            get {
                return this.iD_ClassField;
            }
            set {
                this.iD_ClassField = value;
                this.RaisePropertyChanged("ID_Class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Name_Class {
            get {
                return this.name_ClassField;
            }
            set {
                this.name_ClassField = value;
                this.RaisePropertyChanged("Name_Class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Val_Named {
            get {
                return this.val_NamedField;
            }
            set {
                this.val_NamedField = value;
                this.RaisePropertyChanged("Val_Named");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Val_Name {
            get {
                return this.val_NameField;
            }
            set {
                this.val_NameField = value;
                this.RaisePropertyChanged("Val_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ID_DataType {
            get {
                return this.iD_DataTypeField;
            }
            set {
                this.iD_DataTypeField = value;
                this.RaisePropertyChanged("ID_DataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Name_DataType {
            get {
                return this.name_DataTypeField;
            }
            set {
                this.name_DataTypeField = value;
                this.RaisePropertyChanged("Name_DataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<bool> Val_Bool {
            get {
                return this.val_BoolField;
            }
            set {
                this.val_BoolField = value;
                this.RaisePropertyChanged("Val_Bool");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<bool> Val_Bit {
            get {
                return this.val_BitField;
            }
            set {
                this.val_BitField = value;
                this.RaisePropertyChanged("Val_Bit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<long> Val_Int {
            get {
                return this.val_IntField;
            }
            set {
                this.val_IntField = value;
                this.RaisePropertyChanged("Val_Int");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<long> Val_Lng {
            get {
                return this.val_LngField;
            }
            set {
                this.val_LngField = value;
                this.RaisePropertyChanged("Val_Lng");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<System.DateTime> Val_Datetime {
            get {
                return this.val_DatetimeField;
            }
            set {
                this.val_DatetimeField = value;
                this.RaisePropertyChanged("Val_Datetime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<double> Val_Real {
            get {
                return this.val_RealField;
            }
            set {
                this.val_RealField = value;
                this.RaisePropertyChanged("Val_Real");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<double> Val_Double {
            get {
                return this.val_DoubleField;
            }
            set {
                this.val_DoubleField = value;
                this.RaisePropertyChanged("Val_Double");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<System.DateTime> Val_Date {
            get {
                return this.val_DateField;
            }
            set {
                this.val_DateField = value;
                this.RaisePropertyChanged("Val_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Val_String {
            get {
                return this.val_StringField;
            }
            set {
                this.val_StringField = value;
                this.RaisePropertyChanged("Val_String");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<long> OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
                this.RaisePropertyChanged("OrderID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OServiceClassAttSoapChannel : WpfOnt.OServiceClassAtt.OServiceClassAttSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OServiceClassAttSoapClient : System.ServiceModel.ClientBase<WpfOnt.OServiceClassAtt.OServiceClassAttSoap>, WpfOnt.OServiceClassAtt.OServiceClassAttSoap {
        
        public OServiceClassAttSoapClient() {
        }
        
        public OServiceClassAttSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OServiceClassAttSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OServiceClassAttSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OServiceClassAttSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WpfOnt.OServiceClassAtt.Config[] Config() {
            return base.Channel.Config();
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.Config[]> ConfigAsync() {
            return base.Channel.ConfigAsync();
        }
        
        public WpfOnt.OServiceClassAtt.clsObjectAtt[] ObjectAtts(bool onlyIds) {
            return base.Channel.ObjectAtts(onlyIds);
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.clsObjectAtt[]> ObjectAttsAsync(bool onlyIds) {
            return base.Channel.ObjectAttsAsync(onlyIds);
        }
        
        public WpfOnt.OServiceClassAtt.clsClassAtt[] ClassAttributes(bool onlyIds) {
            return base.Channel.ClassAttributes(onlyIds);
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.clsClassAtt[]> ClassAttributesAsync(bool onlyIds) {
            return base.Channel.ClassAttributesAsync(onlyIds);
        }
        
        public WpfOnt.OServiceClassAtt.clsClassAtt[] ClassAttributesByClassGuid(string guidClass, bool onlyIds) {
            return base.Channel.ClassAttributesByClassGuid(guidClass, onlyIds);
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.clsClassAtt[]> ClassAttributesByClassGuidAsync(string guidClass, bool onlyIds) {
            return base.Channel.ClassAttributesByClassGuidAsync(guidClass, onlyIds);
        }
        
        public WpfOnt.OServiceClassAtt.clsClassAtt[] ClassAttributesByAttributeTypeGuid(string guidAttributeType, bool onlyIds) {
            return base.Channel.ClassAttributesByAttributeTypeGuid(guidAttributeType, onlyIds);
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.clsClassAtt[]> ClassAttributesByAttributeTypeGuidAsync(string guidAttributeType, bool onlyIds) {
            return base.Channel.ClassAttributesByAttributeTypeGuidAsync(guidAttributeType, onlyIds);
        }
        
        public WpfOnt.OServiceClassAtt.clsClassAtt[] ClassAttributesByClassGuid_ttributeTypeGuid(string guidAttributeType, string guidClass, bool onlyIds) {
            return base.Channel.ClassAttributesByClassGuid_ttributeTypeGuid(guidAttributeType, guidClass, onlyIds);
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceClassAtt.clsClassAtt[]> ClassAttributesByClassGuid_ttributeTypeGuidAsync(string guidAttributeType, string guidClass, bool onlyIds) {
            return base.Channel.ClassAttributesByClassGuid_ttributeTypeGuidAsync(guidAttributeType, guidClass, onlyIds);
        }
    }
}
